### ISSUE TITLE
Update the UI so the vertical layout so it fills the page

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#10]
The vertical layout (the default one) currently has a lot of wasted space around the sites.

It would be good to update the UI so that it fills more of the space similar to [JSBin](http://jsbin.com/).

The code and console containers can be extended to fill the page and scale to the users screen size.

**Comment by joshghent** [comment]
Just a reminder that this is still up for grabs! We'd be very welcome of PR's!

**Comment by SaraVieira** [comment]
Hello @joshghent, 

Do you mean vertically and horizontaly? 

Shpuld the padding between the two boxes be removed?

**Comment by joshghent** [comment]
@SaraVieira Yes both horizontally and vertically. Depending on which mode the user has selected.

I believe so yes, ideally we want the divide between the code and console list to be flexible so users can make the code/console window bigger/smaller.

**Comment by SaraVieira** [comment]
Always put both of them at full size and being able to make resize them correct?  

I was also thinking we could do something about the select boxes,  no?

**Comment by SaraVieira** [comment]
Another thing I thought by seeing the site is that I am so used to dark mode on everything that it feels weird to code in white space I guess,  would a dark theme be a good idea?

**Comment by joshghent** [comment]
@SaraVieira Yeah exactly.
I'm not sure about the select boxes, do you have any suggestions?

Yeah we have a dark theme! Just click the moon icon in the top right!

**Comment by SaraVieira** [comment]
As soon as I get back from vacations I will take a look at that,  I will also send you some screenshots to this thread with pics from how it's going so you can approve :)

**Comment by joshghent** [comment]
@SaraVieira Brilliant, thank you very much! Look forward to your PR! Have a nice time on your vacation! 🍹 🏖

**Comment by SaraVieira** [comment]
Thank you and I should get back to you on Sunday or Monday :party-parrot

**Comment by SaraVieira** [comment]
<img width="600" alt="screen shot 2017-02-20 at 17 43 46" src="https://cloud.githubusercontent.com/assets/1051509/23136338/34afe666-f794-11e6-86a3-2ae86ab3a94b.png">

This how it's looking so far, is this what you wanted ? @joshghent

**Comment by joshghent** [comment]
@SaraVieira Looks great! Look forward to your PR. 
Hope you had a nice vacation 🏖

**Comment by SaraVieira** [comment]
https://github.com/esfiddle/esfiddle/pull/52

Please tests and see if you find any issues :)

They were great ! Thank you 💃

**Comment by SaraVieira** [comment]
You can close this issue :)

**Comment by joshghent** [comment]
@SaraVieira Yes thank you. Forgot to close this.

Completed in https://github.com/esfiddle/esfiddle/pull/52
Thanks to @SaraVieira :+1: :tada:
