### ISSUE TITLE
Make navbar ordering consistent

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#100]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
So as we've added pages there has been mixups in pages that are on the navbar and the order of them.

The correct ordering is:
- Profile (only shown when a user is logged in)
- About
- Blog
- Login/Logout (depending on whether the user is logged in)

The best solution would be to create a navbar.ejs file and then include it in all the views.

Also this is issue number 💯  🎉

**Comment by BrianChen** [comment]
@joshghent Hey, I can give this a shot.

I do not see the nav bar on production build.  Is this in the next version?

**Comment by SaraVieira** [comment]
Hey @BrianChen,

That is still in development so you need to build the develop branch

**Comment by BrianChen** [comment]
@SaraVieira gotcha, thanks

I have cloned and have the develop branch set up locally however when I make a change to index.html in the src folder, it also changes in the index.html in the dist folder which causes ../dist/style/es6-fiddle.css?__inline=true to fail to load.

Any ideas on this?

**Comment by SaraVieira** [comment]
Hello @BrianChen ,

It was a paths issue , it's fixed you can pull from develop now 👍

**Comment by vcapretz** [comment]
PR: https://github.com/esfiddle/esfiddle/pull/101
