### ISSUE TITLE
Add how install Mongo DB and NodeJS

### ISSUE THREAD

**Issue by MorrisB--** [esfiddle/esfiddle#108]
#### Type of issue
- [ ] Bug
- [X] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Hello,

I think it would be helpful if the front page had a link to a section that gave some steps on how to install both of these. Maybe it could read like this:

_This guide assumes you already have MongoDB and NodeJS installed. Read this guide (link) if you need help installing them._

If this is a good idea I'd like to take on this task, as I have yet to install MongoDB and NodeJS.

**Comment by SaraVieira** [comment]
Hello! 

You are absolutely right, I'll get on to edit the readme tommorow 

Thank you

**Comment by MorrisB--** [comment]
@SaraVieira Can I try it? I have yet to install these on my end I think it'll be a good learning experience for me to make a guide while doing it

**Comment by SaraVieira** [comment]
@MorrisB-- Of Course you can , all yours man :)

**Comment by MorrisB--** [comment]
@SaraVieira I submitted a pull request, please let me know what changes you'd like and I'll have it done asap, thanks!
https://github.com/esfiddle/esfiddle/pull/109

**Comment by SaraVieira** [comment]
The windows steps are already done thanks to @MorrisB--  and I have done the Mac one's , if someone could do a quick tutorial on how to install mongo on linux that would be great

**Comment by joshghent** [comment]
@SaraVieira @MorrisB-- Yeah great work guys. A Mac and Linux guide should be fairly straight forward (Mac it's just a bunch of brew commands really). Let's create an issue to handle a guide for each platform.

**Comment by SaraVieira** [comment]
@joshghent Mac I already done , just need linux now 👍
