### ISSUE TITLE
Get ESFiddle listed on fiddles.io

### ISSUE THREAD

**Issue by MorrisB--** [esfiddle/esfiddle#110]
#### Type of issue
- [ ] Bug
- [x ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Every fiddle but ESFiddle is listed here, lets get this listed so more people will start using ESFiddle. I can email the owner if this suggestion is approved.

https://fiddles.io/

**Comment by joshghent** [comment]
@MorrisB-- Great idea! Thank you! I've messaged the developer of the site so I'll see if he get's back to me! 👍

**Comment by vcapretz** [comment]
How about this one @joshghent? We still plan to get listed on fiddles.io? Any response from the developer?

**Comment by joshghent** [comment]
@vcapretz Good point! I never got a reply back. I'll chase up and see if I can get in touch. Thanks for the reminder!
