### ISSUE TITLE
Leverage the browser cache

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#112]
According to Google Page speed insights we need to leverage the browser cache for the files below.
These files can probably be added to the `app.use` route that @ironprice91 added in #51 

Below is a screenshot of the files that need caching. More detail can be found [here](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fesfiddle.net).
![image](https://cloud.githubusercontent.com/assets/2934976/25250071/19ef0a9a-260c-11e7-924b-7c4d1f2839dd.png)

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

**Comment by JeffKandel** [comment]
I am going to take a look at this issue over the weekend and next week.  I've been reading about service workers lately and would like some practical experience.
