### ISSUE TITLE
Avoid render blocking JS and CSS requests

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#113]
With the new redesign of the site we introduced a couple of dependancies on fontawesome and ballon.css. We need to make sure these assets are accessed async with the rest of the page and that they do not block the rendering of the page. We want to minimize network requests where available. 

Along with fixing the render blocking requests, bonus points on this PR for having fallbacks for the icons on the page in case the network request to fontawesome times out.

A screenshot can be found below that was taken from Google PSI. The full results for the site can be found [here](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fesfiddle.net&tab=mobile).
![image](https://cloud.githubusercontent.com/assets/2934976/25250404/6537d5f8-260d-11e7-97e3-d0175261d907.png)

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

**Comment by orcutt989** [comment]
@joshghent I'd love to do this one. Not sure where to start though...

**Comment by joshghent** [comment]
@orcutt989 Thanks for looking to help out. [This](https://developers.google.com/speed/docs/insights/BlockingJS) is a good place to start to read up on the issue.

The fix is to make sure that css is inlined into the page. Perhaps we don't need all of ballon css? In addition, the JS should be moved to the bottom of the page, below the closing body tag, therefore it won't block the paint of the page 👍 Come join our [gitter](https://gitter.im/esfiddle/Lobby) if you want to chat

**Comment by orcutt989** [comment]
@joshghent Which page needs the changes?

**Comment by joshghent** [comment]
@orcutt989 I believe just the homepage, but others may need changing also. Check them out on google PSI 👍

**Comment by collinmesser** [comment]
@joshghent Looking for my first OSS pull request. I can knock this out if it's still open? I joined the gitter as well.
