### ISSUE TITLE
Improve styling of the About page

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#114]
The styling of the about page needs improving to be more consistent with the rest of the site. Take a look at the blog to see what fonts we use for text. We will be adding more content to this page in the near future so make sure it's flexible to any amount of content.

I also noticed a slight bug when my friend was visiting the site, the footer bar of the page does not seem to be completely sticky to the bottom. On this particular resolution (17-20" iMac I believe?) it was up the page by about 100px. Take a look into that too whilst you're working on this issue 😜

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

**Comment by madhankumar028** [comment]
@joshghent I will work on this. Will let you know if I need any support.

**Comment by piyush7749** [comment]
@joshghent Looks like this issue is still open. Can I work on this? I am looking for a beginner friendly bug to get started in contributing to open source projects!

**Comment by evanscloud** [comment]
@joshghent first timer here, am I able to work on this or is it taken? If it's still open, I'd like to work on this.

**Comment by joshghent** [comment]
@evanscloud All yours friend! Let us know if you need any help.
