### ISSUE TITLE
Add F.A.Q of common issues and their solutions to the contributors guide

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#116]
There a few common problems people encounter when first getting started with contributing on the project. For example if you clone the repo down and run `npm start` it will throw an error which does not point to an obvious solution (`npm install` in this case). 
The worst offender here is when you have not started mongodb in another terminal tab and it throws a really random error about sockets or something. I've even been caught out by this one on occasion!

### **First timers, don't fear!** 
You're the **best** people to handle this issue. Try and go through the contributing guide and really make sure it's watertight, bulletproof and battle-hardened. **Non-native english speakers are especially welcome** here as we want to make sure it's easy for you guys too!

**Comment by rosnovsky** [comment]
Let me take this, @joshghent. Any specific requirements, formats or conventions to follow here?

**Comment by joshghent** [comment]
@rosnovsky Nope not really. Make it easy to follow and presentable. Feel free to use screenshots or any other material you feel will help (for example you could include a further reading section or something).

Thanks a lot for looking into this!

**Comment by harshaiitr** [comment]
@joshghent I will like to work on this if the issue is yet not fixed and this will be my first contribution in open source.

**Comment by asiyani** [comment]
@harshaiitr Ya please go ahead, this one is all yours.
Let us know if you need any help. 
Thank you.

**Comment by joshghent** [comment]
@harshaiitr Yeah sounds great, we'd love to have your help!

I wrote some content for this page but forgot to post it here. Feel free to use it and/or add to it!

> **What does ES in ESFiddle stand for?**
> It stands for ECMAScript - the language on which Javascript is based off of. When the TC39 (Technical Committee 39) ,who manage what goes into the language of ECMAScript, introduce a new feature to the language, it is the job of the browser makers to implement it. Because this takes time and can vary across browsers we created ESFiddle to try out these new features before they are implemented in the browser.
> 
> **How does ESFiddle work?**
> It takes your code that you write on ESFiddle and runs it through the babel transpile library to convert that to javascript that your browser can run.
> 
> **Who makes ESFiddle?**
> These amazing people. We work entirely online through github. You can see the repository here. You can even come and chat with us here. We come from all over the world in places like Brazil, Portugal, England, US and India.
> 
> **Cool! Can I help?**
> Absolutely, we'd love to have you on board! Check out issues board and look for any that take your fancy. Or if you want to suggest and feature/bug fix then create a new issue and we will take a look into it.

**Comment by rosnovsky** [comment]
Could someone pleas take a look at #137? I'm not sure it's what's expected. Also, I apologize that it took me so long to actually get started :(

**Comment by joshghent** [comment]
Hey @rosnovsky I've merged that for you now. Looks great, thanks for the work.

We will continue to add to this document so we will still take PR's for it.

If you are able perhaps look into writing answers for the following questions
- What is the error I get when starting the server without mongo open and how can I fix it?
- My code has failed on TravisCI, how can I fix and test changes quickly? (hint: `npm test`)
- Do I have to write tests for new code I write (hint: yes ideally if appropriate, for design changes -> no)

**Comment by satyadeeproat** [comment]
Hi @joshghent , just installed the esfiddle from scratch. Didn't find any problem as such. The documentation was up to the mark. Just one thing. Can we update the GETTING STARTED section in  README.md because I didn't find the npm install step in it. Well it's an obvious thing to do. But forgot to do it that time. Then I saw the contributing guide which helped me to realize that npm install is needed

**Comment by joshghent** [comment]
@satyadeeproat That's a good idea. I'll do that. Perhaps we can add it to the npm prestart.

**Comment by Govorin** [comment]
Hi. I  want to help you, if possible. Can you give me tasks?
Im beginner and non-native english speaker.

**Comment by joshghent** [comment]
Done in #173
