### ISSUE TITLE
Improve the visibility of the divide between the code and console window

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#117]
Very small one here, there is a divide between the code and console window. However, when the theme colors match (either dark and dark or white and white) then the divide is difficult to define. And since we have a feature to resize the windows, this function is not very apparent.

The solution here is to make the line visible but not too bright as to detract attention from the rest of the site. 

I've included a screenshot below.
![image](https://cloud.githubusercontent.com/assets/2934976/25251499/73d65d56-2611-11e7-839b-6c414cd619b1.png)

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

**Comment by jaycobbcruz** [comment]
Hello @joshghent . Can have this work? Please see screenshots taken after updating few lines in less.

<img width="1270" alt="screen shot 2017-05-02 at 9 57 01 am" src="https://cloud.githubusercontent.com/assets/25121666/25601325/cf6f690e-2f1d-11e7-9e5c-89509e24a693.png">
<img width="1266" alt="screen shot 2017-05-02 at 9 57 22 am" src="https://cloud.githubusercontent.com/assets/25121666/25601328/d7787a00-2f1d-11e7-9466-9dc5932210b5.png">

**Comment by orcutt989** [comment]
@joshghent Looking for new projects to contribute to, but it looks like this one is resolved.

**Comment by joshghent** [comment]
@jaycobbcruz Looks good! Submit a PR and we can review the code! Thanks for your work! 🎉 

@orcutt989 Yes looks like it! We have lots of other issues you can sink your teeth into. Or suggest a feature/bug fix! We are always looking for new tests for our code base, that's a good place to start!
