### ISSUE TITLE
Make esfiddle profiles publicly accessible 

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#119]
We want to make esfiddle profiles accessible to anyone so they can see each others fiddles. 

This will require new API methods and routes to get a unique URL for each user (I recommend we use the mongo _id that is assigned to each user record.

We also need to add extra logic to the profile page to make sure that private fiddles are not shown in the users list of fiddles if they are not logged in as that user! For example if I am logged in as myself I should be able to see **ALL** of my fiddles, public or private. If someone else views my profile they should only be able to see public fiddles.

If you need any help with this issue then please let us know. We'd be happy to help. You can also check out our [contributing](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) guide 👍

**Comment by JeffKandel** [comment]
Hiya,

I would like to take a look at this issue.  I have a vacation next week and was hoping to dive in then. Is that cool?  I have taken a look at the CONTRIBUTING.md and will post any additional questions when they come up.

**Comment by joshghent** [comment]
@JeffKandel Sure thing dude, we'd be happy to have your help! Have a great vacation! 🏖
