### ISSUE TITLE
Configure OpBeat APM

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#12]
So I've added Opbeat APM to add some performance monitoring for us. I believe this allows me to be notified when the app is down so I can kick it back to life.

However it needs configuring. Simply follow the guide here
https://devcenter.heroku.com/articles/opbeat#using-with-node-js

**Comment by kaustubhmallik** [comment]
Hey josh, I checked the Heroku link you and the official documentation for [OpBeat APM](https://github.com/opbeat/opbeat-node#user-content-quick-start)]. I think creation of OpBeat agent need to be configured with your app-id, org-id and secret token, in order for you to see you app stats. 

So, I think you should [register your app](https://opbeat.com/nodejs)] and store the required fields in a config file or somewhere (obviously you don't want to share them), where I can access them from my javascript.

**Comment by joshghent** [comment]
@kaustubhmallik Great work, thanks a lot. I'll take a look into this tomorrow 👍

**Comment by kaustubhmallik** [comment]
Sure buddy. Let me know if I can help further on this otherwise I will try to work on some other issue.

**Comment by vanjacosic** [comment]
Hey @joshghent and @kaustubhmallik,

Sorry to comment on a closed issue but I thought I'd get in touch with you here.

I'm the Community Manager at Opbeat and I noticed that you guys are working on esfiddle and trying out Opbeat for it.
We like to support open source projects like yours. So if you are serious about using Opbeat, I can help you get started and set up a fully featured plan for free for the project.

Let me know if you're interested and we can talk.

Keep up the good work!

**Comment by kaustubhmallik** [comment]
Hi @vanjacosic, its really great what you are offering us. Looks good opportunity to collaborate and explore about this. Waiting for @joshghent reply.

**Comment by joshghent** [comment]
Hi @vanjacosic No problem! Thanks for reaching out! 

Yeah that would be great. I honestly closed the issue because I did not have time. I will make this more of a priority. 

What would be involved in getting setup?

**Comment by ageddesi** [comment]
Let me know if you need any help with this.

**Comment by vanjacosic** [comment]
We just need to get you guys set up on a new organisation and get the app deployed with the Opbeat agent installed and the tokens configured. We can help out with that 😄 

@joshghent, can you create an Opbeat account and then press the Help link in the top. That will let you start a chat with support. I or one of my coworkers can then see the conversation and help you get set up.

Remember to mention me or reference this conversation when you write us.

**Comment by SaraVieira** [comment]
@joshghent Are we still going to do this ?

**Comment by SaraVieira** [comment]
@joshghent?

**Comment by joshghent** [comment]
@SaraVieira This is quite a big job and we need to decide what monitoring we will doing. I haven't really had time to look into the full capabilities of OpBeat yet but it's on my list.

**Comment by isaeef** [comment]
@joshghent  is it still open?

**Comment by joshghent** [comment]
@isaeef Yeah this is something I've just not had time to do. We also got approved for a OS Bugsnag account but need to figure out how to configure this without more setup people have to do with api keys.
