### ISSUE TITLE
Improve Small Screen Support

### ISSUE THREAD

**Issue by ageddesi** [esfiddle/esfiddle#123]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
We need to improve the new design to work on smaller screens and mobile. 
As you can see a scroll gets attached to the menu and there is a white gap.

![screen shot 2017-04-27 at 14 14 49](https://cloud.githubusercontent.com/assets/1301564/25484993/165c3d7e-2b54-11e7-8eb9-b611615eab1f.png)

**Comment by SaraVieira** [comment]
Hello @ageddesi, 

How could I miss that? Shame! I will get cracking on that :) 

Thank you

**Comment by ageddesi** [comment]
@SaraVieira I do frontend all day long and I always miss something lol. :)

**Comment by asiyani** [comment]
@joshghent I am not able to replicate this issue. I think this one is fixed.

**Comment by ahmadtirmazi** [comment]
Hi @joshghent, 

I am able to reproduce the scroll bar appearing in menu bar. 

I am new to this project and want to take on this as my first bug.
Please let me know if I should work on this.

**Comment by joshghent** [comment]
@ahmadtirmazi Yeah we'd love to have you work on this issue. That would be a great help to the project! 🎉 

Let us know if we can help 👍

**Comment by ahmadtirmazi** [comment]
@joshghent, I am having trouble while trying to run in my local environment. 
I have followed the instructions explaining the steps to configure local environment and configured NodeJS and MongoDb.

To start the project, I run "mongod" and in another command prompt "npm start".
However, I get following error

![image](https://user-images.githubusercontent.com/16874651/27354460-134cf2a2-5621-11e7-8b97-c9e5f826656e.png)

I have tried looking around but no luck.
Can you please share your thoughts on this?

**Comment by rosnovsky** [comment]
Hi @ahmadtirmazi,

Could you please make sure you point MongoDB to wherever your database is? I've experiences similar problem when my db folder was set incorrectly (specifically, the db path on my Mac was not set to /usr/local/var/mongodb.)
 
https://github.com/esfiddle/esfiddle/blob/develop/docs/FAQ.md#ive-got-some-mongoerror-messages-and-esfiddle-doesnt-load

**Comment by rosnovsky** [comment]
Hi @ahmadtirmazi,

Could you please make sure you point MongoDB to wherever your database is? I've experiences similar problem when my db folder was set incorrectly (specifically, the db path on my Mac was not set to /usr/local/var/mongodb.)
 
https://github.com/esfiddle/esfiddle/blob/develop/docs/FAQ.md#ive-got-some-mongoerror-messages-and-esfiddle-doesnt-load

**Comment by asiyani** [comment]
Hi, @ahmadtirmazi  You might get this error if you don't have  `.env`  file in your root directory. please rename `sample.env` to `.env` if you don't have one already.

**Comment by joshghent** [comment]
@asiyani Let's add this to the FAQ

**Comment by ahmadtirmazi** [comment]
@rosnovsky, I had already set the correct db path. 
Though, as suggested by @asiyani, renaming `sample.env` to `.env` solved the problem.

Thanks for the help guys.
