### ISSUE TITLE
Issues to start the project.

### ISSUE THREAD

**Issue by VijayVj7** [esfiddle/esfiddle#125]
#### Type of issue
- [x] Bug- Unable to start the project
- [x] Idea/Suggestion-I'm stuck at mongod --dbpath c:\data\db
- [x] Question--How do I proceed further

#### Description (include any screenshots or debugging information if applicable)
I'm stuck at 
![image](https://cloud.githubusercontent.com/assets/18487229/26122875/98bfb4de-3a96-11e7-9b40-4ce60402e257.png)

Step: my dbpath is C:/data/db
         
![image](https://cloud.githubusercontent.com/assets/18487229/26123062/46a51bfc-3a97-11e7-8598-1c411a40cdbc.png)
        
Next Step: When I placed the command in cmd prompt, following error is being displayed
![image](https://cloud.githubusercontent.com/assets/18487229/26123423/7703a2cc-3a98-11e7-9449-3f0af01f30c5.png)

So could send me the entire procedure of starting the application.. that really helps the first timers

Please do help us

**Comment by joshghent** [comment]
@VijayVj7 Hi there, Thanks for the suggestion! We are looking to improve our documentation in the near future.
From looking at this image, it appears to be just kicking up a warning. If you check the penultimate line it says `Waiting for connections on port 27017` which is correct. Try opening a new terminal window and run `npm start` and see if it works. If not, screenshot it and post it here.

**Comment by VijayVj7** [comment]
Step 1: Opened Git Bash, 
           run  -->    mongod dbpath c:/data/db
           
![image](https://cloud.githubusercontent.com/assets/18487229/26168617/56fcb214-3b58-11e7-9b83-3b618c40b5c8.png)

Step 2: Open a new terminal window and run npm start.Error was thrown.
![image](https://cloud.githubusercontent.com/assets/18487229/26168870/52836a88-3b59-11e7-815e-ed56b7a58381.png)

Could you just help me out :(

**Comment by joshghent** [comment]
@VijayVj7 First of all, nice computer name you got there 😅

It looks like your running npm start in your root directory. Make sure you are `cd`'ed into the project folder and **then** run `npm start`

**Comment by VijayVj7** [comment]
Step 1:when running mongod --dbpath c:/data/db

![image](https://cloud.githubusercontent.com/assets/18487229/26216660/867e3e48-3c22-11e7-9e0d-4604ce1145ea.png)


Step 2: path is "cd [project root directory]" and ran " npm start" following error is displayed.
![image](https://cloud.githubusercontent.com/assets/18487229/26216632/6bc65374-3c22-11e7-9bb6-4ddc8e4953bf.png)


Damn!! I'm so frustrated that I'm unable to do anything. tried tried tried and tired
Help me ! Help you

**Comment by asiyani** [comment]
Error message on last screen shot is becz its unable to find "load-grunt-tasks".
1 ->  in package.json file you should have `"load-grunt-tasks": "^3.5.2"` in devDependencies.
2 -> Did you got any error message when you did npm install in esfiddle directory?
3 -> Do you have folder called "load-grunt-tasks" in to your "node_modules" folder ?

Solution -> I would suggest Delete node_modules folder., make sure your package.json file is matching one on github and do `npm install` again, make sure you are in esfiddle root directory.

**Comment by joshghent** [comment]
@VijayVj7 Getting frustrated at us and yourself will not help anything. Please be constructive with your responses.

Make sure you have followed our setup guide. Did you run `npm install` in the project directory before running `npm start`? If you have then follow as @asiyani has said.

Either way, review the[ setup guide](https://github.com/esfiddle/esfiddle/blob/develop/docs/CONTRIBUTE.md) please. Make sure you've followed the steps.

**Comment by VijayVj7** [comment]
Well I was never frustrated on you ppl, I knew that I was doing some
mistake and I don't know where I was missing it. I will try it again.

**Comment by VijayVj7** [comment]
Hi All,
Finally got it brother..!!
I am so thankful to Asiyani, Ashok and Josh for helping me out!!

**Comment by VijayVj7** [comment]
I've made a pull request with command "$ git push --set-upstream origin
add-vijay-kumar" which is the last command.Is there anything else I should
do? and when will merges will happen to master branch
I have few questions to ask
1)I couldn't those changes in my git hub fork why?
2)Am I doing the PR process correct?

Please revert back !!
Thank you

**Comment by VijayVj7** [comment]
I've made a pull request with command "$ git push --set-upstream origin
add-vijay-kumar" which is the last command.Is there anything else I should
do? and when will merges will happen to master branch
I have few questions to ask
1)I couldn't see those changes in my git hub fork why?
2)Am I doing the PR process correct?

Please revert back !!
Thank you

**Comment by asiyani** [comment]
Hi @VijayVj7 
Please check comments on PR for an update. 

Regarding Questions about PR Process. 
They way I do this is first I will commit all changes to into my fork, push it on GitHub and then submit PR via GUI on the website. 

Thank you.
