### ISSUE TITLE
navigators are using different font family when when navigated from About -> Blog 

### ISSUE THREAD

**Issue by VijayVj7** [esfiddle/esfiddle#126]
#### Type of issue
- [1 ] Bug
- [x] Idea/Suggestion--We need to make them consistent
- [x] Question--Is this a valid bug?

#### Description (include any screenshots or debugging information if applicable)
Screenshot:
![image](https://cloud.githubusercontent.com/assets/18487229/26274164/ca460720-3d60-11e7-8225-6cb8c9756a27.png)

When navigated to blog
![image](https://cloud.githubusercontent.com/assets/18487229/26274169/e1e81cba-3d60-11e7-9a8e-f311ed8599cf.png)

I would like to work on this!!

**Comment by joshghent** [comment]
@VijayVj7 Good spot! Yeah go ahead. Make sure all the navbars have the same font as on the blog - I think I like that better.

**Comment by asiyani** [comment]
I think this one is now fixed after #128 
@joshghent could you please re-test just to be sure and close this issue.
