### ISSUE TITLE
UI improvement ideas

### ISSUE THREAD

**Issue by asiyani** [esfiddle/esfiddle#131]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
To prepare for 4.0 #120, we need to make some UI changes. 
For this issue, we are just looking for some suggestions or mockups. 

What we need: 
  1. All existing console buttons. 
![image](https://cloud.githubusercontent.com/assets/7142320/26763308/c5c36046-4948-11e7-9de5-01529465226e.png)

  2.  Textfield for fiddle Title and Description.  #102
  3.  UI component to Add 3rd party Library and display added 3rd party library. #46
  4.  Maybe move ES6 examples drop down to own page.

**Comment by babzcraig** [comment]
Hello guys, I'd like to take a stab at this if it is still open. How do we submit our ideas? I am able to use Sketch to create mockups if needed.

**Comment by joshghent** [comment]
@babzcraig Sorry for not getting back to you. If you post pictures of sketch mockups here then we can review them and get building them! Perhaps you could even take a shot at building them? We'd greatly appreciate any help here as I'm not really one for graphic design 😆

**Comment by babzcraig** [comment]
@joshghent No worries, I can get to work on this over the weekend and have something for you by next week, does that work? And sure, designing and building out my designs wouldn't be a problem. 😆

**Comment by joshghent** [comment]
@babzcraig Yeah that's absolute no problem, no rush! We all do this in our spare time and also have loved ones and other obligations so see them first then work on this 👍 
Haha ok brilliant, look forward to seeing it!

**Comment by joshghent** [comment]
@babzcraig Hey there, I kind of let this issue drift but wanted to check in to see if you were doing ok with your PR and this issue? Can I or anyone else in the team help? Contact me on gitter if you need any assistance! 👍 

If you no longer have time to work on it, that's fine too. We appreciate people generously donate their precious free time to this!
