### ISSUE TITLE
Footer doesn't stick to the bottom of blog page

### ISSUE THREAD

**Issue by evanscloud** [esfiddle/esfiddle#135]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

![footer issue](https://user-images.githubusercontent.com/15055726/27053873-f3fe7f96-4f8c-11e7-932f-cd01e2ca601c.jpg)

While working on issue #114, I noticed that, as the resolution gets larger, the footer doesn't stick to the bottom of the page.

**Comment by joshghent** [comment]
@evanscloud Thanks for reporting this. Good spot! Feel free to work on it if you want 👍
