### ISSUE TITLE
Optimize profile for mobile

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#141]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

The profile needs a redesign especially considering it doesn't look very good on mobile and on desktop I don't think it uses the space as well as it could. Go wild with this one and be adventurous! Idea's are encouraged even if you cannot implement it. 

Information we need to have accessible on the profile
- Recently created fiddles
- Starred fiddles
- Private fiddles (if you are logged in as that user)

If you want a second thought before you start also, then please just reply with a screenshot and we'll jump in with feedback!

![capture](https://user-images.githubusercontent.com/2934976/27406485-e610a3cc-56cc-11e7-93ba-7c2c56d3c983.PNG)

**Comment by colinxr** [comment]
Hey is this still open? I'd like to take a stab at it!

**Comment by joshghent** [comment]
@colinxr Sure go for it! We'd be very grateful for your help.

**Comment by youssefsharief** [comment]
Hello @joshghent,
Is this still open ?

**Comment by joshghent** [comment]
@youssefsharief Yeah sure, I believe @colinxr is working on this but is busy working. Maybe get in touch with him on our gitter and see if you can assist in anyway 👍

**Comment by colinxr** [comment]
@joshghent @youssefsharief Hey guys, things were basically ready – I just had not submitted the pull request. Sorry for the delay.

**Comment by zamhaq** [comment]
@joshghent Is this issue fixed or still open ? I would like to take an attempt.
