### ISSUE TITLE
Drop down from setting icon is hiding in mobile view

### ISSUE THREAD

**Issue by satyadeeproat** [esfiddle/esfiddle#142]
#### Type of issue
- Bug

#### Description (include any screenshots or debugging information if applicable)
I just checked the mobile version of the site and the setting icon drop down was hiding behind the code section. 
![screen shot 2017-06-24 at 7 18 48 pm](https://user-images.githubusercontent.com/10433604/27509235-dc8d6b50-5915-11e7-92c5-7590dcf4aebd.png)

I also tried checked on the mobile the site and facing the same issue.
Browser: Checked both on Firefox and Chrome
OS: Mac Sierra
Mobile OS: Android Marshmallow

I think the issue is with the z-index of drop down
Thank You

**Comment by slntRohit** [comment]
Hi. I was hoping to contribute here but I think this has already been fixed by #123

**Comment by joshghent** [comment]
@slntRohit This still seems to be an issue on https://esfiddle-dev.herokuapp.com! If you'd like to take a stab at fixing it then by all means go ahead, we'd greatly appreciate your generous contribution.
