### ISSUE TITLE
Blog Posts!

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#145]
We are looking for blog posts for the [ESFiddle blog](http://esfiddle.net/blog)!

Fancy writing for us?

Great, simply reply to this issue with your blog post idea - we are primarily looking for blog posts around Javascript, ECMAScript and broader subject posts about open source software (for example I might write one about running an open source project). These blog posts can be tutorial (e.g., how to currying in ES6) or more news focused posts (e.g., New features of ES7).

This is a great way of contributing even if you can't code! We will treat this as any other code contribution! It's just as valuable, if not more so!

Please pass this onto any friends who may be interested! We would love to have interested people on board!

**Comment by zamhaq** [comment]
hey I would like to write a blog post about es6 features ? Would it be helpful?

**Comment by joshghent** [comment]
@zamhaq Yeah that sounds great. We already have @SaraVieira writing an article on the spread operator but you're article would be most welcome!

Perhaps suggest where people could use these new feature! Practical application is always helpful to people (or at least me 😄)

**Comment by j-schuster** [comment]
Hey! If you want anything else written I would love to help out:)

**Comment by joshghent** [comment]
@j-schuster Hey there, thank you for offering! A post on the feature set for ES8 would be very helpful! Especially as the new spec has just come out!

A few other topics could include
- How does ESFiddle work? (might be a good one to get you under the hood of the code)
- Who creates ECMAScript? (talk about the TC39 and the members, the stages system etc.)
- Is Javascript the same as ECMAScript?

Just a few ideas! Hopefully that keeps you going! 😁 We would be very grateful for any blog post contributions at this stage 👍
