### ISSUE TITLE
Starred fiddles list appearing twice on profile page

### ISSUE THREAD

**Issue by JeffKandel** [esfiddle/esfiddle#146]
#### Type of issue
- [X] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

When a user logs in, the starred fiddles list appears twice on the profile page.  

The second time it is misspelled.

Screencast here: https://screencast.com/t/k8QvpdclIUb

**Comment by Logan1x** [comment]
So should it be once or spelled correctly? @JeffKandel.

**Comment by JeffKandel** [comment]
One time and spelled correctly would be best.

**Comment by Logan1x** [comment]
@JeffKandel Can you give me some idea for starter i dont know js.

**Comment by zamhaq** [comment]
@JeffKandel I would like to work on the issue but I am not able to reproduce the error.
![prof](https://user-images.githubusercontent.com/20766601/28260322-22704702-6af8-11e7-980f-639e1f62f236.png)

**Comment by JeffKandel** [comment]
@zamhaq, I think this is what the profile should look like.

Can anyone else reproduce this issue or is it only me? 

Here is a new screenshot with the URL I am on.  I was in Chrome for the earlier screenshot.  This second screenshot is in Firefox.  Let's include the URL and browser info going forward so we can ensure we are looking at the same thing.

https://screencast.com/t/OwjtjqVfI1

**Comment by JeffKandel** [comment]
@Logan1x, welcome to esfiddle!   To get started, I would do the following things:
1)  Try to reproduce the issue.  If you aren't able to, please let us know.
2) Check out the file in the repo at /docs/CONTRIBUTING.md this will help you set up your dev environment.
3) If you ARE able to reproduce the issue, I suspect it will be a problem in the /views/profile directory so I would look there to see if I can find what in the html is causing this problem.  We use the EJD templating language so you may have to read a bit about that.  When you think you've found the cause, you can either try to code a solution or ask me for more guidance.  I'm happy to help.

**Comment by zamhaq** [comment]
@JeffKandel Ok. I can see it now. Strange why the bug was not showing up earlier.

**Comment by Logan1x** [comment]
@zamhaq  you should ask in their gitter group.

**Comment by JeffKandel** [comment]
@zamhaq there is a file called sample.env in the repo.  If you open it up it included some information about logging in on your local environment.  I found it hard to find as well, but once you follow the instructions you're good to go.

**Comment by zamhaq** [comment]
@JeffKandel Do I have to register the application with github ? Only then can I get the github client ID and client secret right ? Or is there any other way ?

**Comment by JeffKandel** [comment]
Yep, you'll have to register an OAuth app. Here are the options I used:

App Name: esfiddle
Homepage URL: http://localhost:3001
Authorization callback URL: http://localhost:3001/auth/github/callback

**Comment by zamhaq** [comment]
@JeffKandel So, the callback URL should be that same localhost with "/auth/github/callback" exactly?

**Comment by JeffKandel** [comment]
Yep, the same values I used should work...  I'll check in tomorrow morning in case there are additional questions!

**Comment by zamhaq** [comment]
@JeffKandel I tried as you suggested but getting this error 
`InternalOAuthError: Failed to fetch user profile
    at /home/zams/esfiddle/node_modules/passport-github2/lib/strategy.js:96:19
    at passBackControl (/home/zams/esfiddle/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/zams/esfiddle/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by zamhaq** [comment]
@JeffKandel I solved the issue for wrongly spelled issue though could not reproduce that double starred fiddles in local environment. Should I submit a PR ?

**Comment by JeffKandel** [comment]
Hey Zameer,

I think so.  If nothing else, we have fixed the misspelling.  If everything passes, I'll take a quick look through things to see if I can reproduce the issue on my local machine.  Thanks for the help!  I'll leave some comments in the PR too before we merge.

Jeff

**Comment by zamhaq** [comment]
Hey Jeff, 
Should I submit my PR then?

**Comment by JeffKandel** [comment]
Yep!
