### ISSUE TITLE
Specify engines version in packagejson

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#148]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
With the new batch of [security releases](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/) from NodeJS, we need to specify the versions of node we use in the package.json file. This can be done under a label of "engines". 

We need to specify the following versions of node that can be used (and we support as shown in our .travis.yml)

1. Latest
2. v7
3. v6

**Comment by austinjcheng** [comment]
I attempted this as best as I could, but I'm not fully confident in the labels that I used. I was also unsure of how to fully complete the pre-submission checklist. If any changes are needed please let me know.
