### ISSUE TITLE
Linting errors in default examples

### ISSUE THREAD

**Issue by amatranga** [esfiddle/esfiddle#153]
#### Type of issue
- [X] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
There are a few linting errors in some of the default examples.

ES6 Map

![image](https://user-images.githubusercontent.com/24361338/28351902-e38621d6-6c07-11e7-8faa-1e0413407c7b.png)

ES7 Array Includes: Search From Index

![image](https://user-images.githubusercontent.com/24361338/28351917-ff4af9b4-6c07-11e7-9810-447b60ba5919.png)

The Map linting error seems to be from a couple missing semi-colons.

The Array Includes: Search From Index linting error is from having an empty index in the example array. Changing it to 'undefined' fixes the error, but might not be in the spirit of the example. Could this be clarified?

These are both quick fixes, which I'm happy to get a PR up for

**Comment by vcapretz** [comment]
Hi @amatranga, feel free to send the PR!
