### ISSUE TITLE
Running eslint on server throws a lot of errors 

### ISSUE THREAD

**Issue by vcapretz** [esfiddle/esfiddle#156]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
I just realized that we have eslint setup but we don't actually included it in the `test` command.

I ran `./node_modules/eslint/bin/eslint.js server/**` and found a lot of inconsistentes. 

I am already working on it but let me know if you guys have any thoughts

**Comment by amatranga** [comment]
Related to what we were talking about in [#158](https://github.com/esfiddle/esfiddle/issues/158), I've gotten spacing issues taken care of client side. The major linting issues coming up now are related to .less files (too many !important declarations, no fallback set in addition to rgba). So I am going to go ahead and make a partial PR, and get the other linting issues taken care of in another PR

**Comment by vcapretz** [comment]
it makes sense @amatranga, I saw those errors, glad that you are going to take care of it
