### ISSUE TITLE
Code-base styling

### ISSUE THREAD

**Issue by amatranga** [esfiddle/esfiddle#158]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

Looking thru the code-base, there are a bunch of inconsistencies between files. For example, some files have 4 spaces of indentation while others have 2; some files use 2 new-lines between functions while others use 1; some files close scopes every new-line while others close scopes every other new-line.

Ultimately, I would like to recommend a STYLE-GUIDE.md file. If I can make a recommendation, it would be [this one here](https://github.com/amatranga/PepClock/blob/master/STYLE-GUIDE.md)

Once a style guide is decided on, it should be added to the repo, and mentioned in the README, probably under 'contributing'

**Comment by vcapretz** [comment]
I opened an issue about the same topic today! I am focusing now on the server-side but we could also check the client side! 

You can check the issue here: https://github.com/esfiddle/esfiddle/issues/156

**Comment by amatranga** [comment]
@vcapretz I'm happy to take a look at client side if you'd like. I know there's a bunch of work to be done.
And I did see the issue you opened. I thought it would make more sense to open a separate issue though

**Comment by vcapretz** [comment]
Ok then! ☺️ You can use this issue to work on client side then, would be happy with your help!

**Comment by amatranga** [comment]
Will do! I'll start looking at the client.

Related: What do we think about adding in a style guide?

**Comment by vcapretz** [comment]
How about using the eslint that is already on the project setup? It extends the airbnb pattern. 

Another thing you could do is to check if we are using the ES6 features! 

Feel free to send the PR

**Comment by amatranga** [comment]
Good point about ES6. The guide I linked definitely does not use it.
I'll update and send along a PR
