### ISSUE TITLE
Suggestion: change README.md so sample.env is not deleted

### ISSUE THREAD

**Issue by eugenefedoto** [esfiddle/esfiddle#165]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Currently, the readme instructs the user to delete sample.env. This is annoying to me because then Git complains that this file was deleted and wants it to be staged. It should never be staged, otherwise it will be deleted from Github. In addition, it's always good practice to keep sample.env as a backup.

Currently:
mv sample.env .env

My suggestion:
cp sample.env ./.env

**Comment by joshghent** [comment]
@eugenefedoto Great idea! I've seen your PR for this and will get it merged.
Thanks a lot for spotting this, good work 🎉
