### ISSUE TITLE
Bug: several wrong uses of ES6's object destructuring

### ISSUE THREAD

**Issue by eugenefedoto** [esfiddle/esfiddle#167]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
I ran `npm test` and received several similar errors like 
```
/home/eugene/esfiddle/test/api.test.js:4
const { expect } = require('chai');
      ^

SyntaxError: Unexpected token {
```
That should be const `expect = required('chai').expect;`. There were several more.

**Comment by eugenefedoto** [comment]
I found out I was using an out-of-date Node v4. After I updated to v8, everything became fine.

**Comment by joshghent** [comment]
@eugenefedoto Thanks for looking into this, glad you got it sorted. Maybe this is something to include in the README?

**Comment by eugenefedoto** [comment]
@joshghent Yep. I opened #170.
