### ISSUE TITLE
Developer branch missing dist/lib/babel/

### ISSUE THREAD

**Issue by eugenefedoto** [esfiddle/esfiddle#168]
#### Type of issue
- [ ] Bug
- [ ] Idea/Suggestion
- [x] Question

#### Description (include any screenshots or debugging information if applicable)
Is there a reason why the developer branch is missing dist/lib/babel/? The master branch has it.

**Comment by joshghent** [comment]
Yes this was because I was dumb. It needs re-adding.
I was trying to remove it entirely but didn't manage it in the time I had. We need to open a new issue to get that addressed (we don't want to be including babel in the repo!)

For the time being, let's just get back the babel folder in the repo. If you would like to handle that we would be more than willing to accept a PR! 👍

**Comment by riyaz-ali** [comment]
Won't it be better if we just serve the file from a CDN instead? It's available [here](https://unpkg.com/babel-standalone@6/babel.min.js). And to add it we just need to update the address [here](https://github.com/esfiddle/esfiddle/blob/develop/src/js/index.js#L311).

**Comment by joshghent** [comment]
@riyaz-ali Yes that is completely the best way to do it. I believe this is part of your PR #171 - is that correct?

**Comment by riyaz-ali** [comment]
@joshghent Yea I tried adding the linked Babel bundle to the iframe sandbox, but it looks like that version don't include (or maybe didn't load by default) some of the required plugins (e.g. regeneratorRuntime for Generator functions and possibly more), so instead I resorted to use the same (old) script for now. But this is certainly a good candidate for a fix!!

**Comment by joshghent** [comment]
@riyaz-ali Ok, if you want to have a crack at fixing that and providing it through a CDN then that would be helpful! I remember when I tried to have a go at doing it, the issue was they didn't export a 'Babel' object which we then use internally.
