### ISSUE TITLE
Add eslint to grunt test task

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#17]
We have an eslint config but it is currently not tested against when we run `grunt test`

Using [this package](https://www.npmjs.com/package/grunt-eslint) we can test src/es6-fiddle.js for eslint errors.

This will mean that future PR's are always kept to the code base standard.

**Comment by tarang9211** [comment]
hey! im new to grunt, but could i take a shot at this?

**Comment by joshghent** [comment]
@tarang9211 Yeah sure thing. The code will be reviewed before merging so go for it 👍

**Comment by tarang9211** [comment]
@joshghent i created a PR for this [here)(https://github.com/esfiddle/esfiddle/pull/20)

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/20
