### ISSUE TITLE
Console Logging an object/map should log the literal.

### ISSUE THREAD

**Issue by nickinnon** [esfiddle/esfiddle#176]
#### Type of issue
- [ ] Bug
- [ x ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

Right now, the console in the ESfiddle client prints out `[object Object]` or `[object Map]` when logging an object or map respectively. 

This behavior persists for the browser's console as well, where the normal behavior would be to log the literal.

Would love if this could be changed to show the object literal in the console for at least the browser's console.

Current behavior
```
const obj = {foo: 'foo'};
console.log(obj);        // [object Object]

const map = new Map();
map.set('foo', 'foo');
console.log(map);        // [object Map]
```

Proposed 
```
const obj = {foo: 'foo'};
console.log(obj);        // {foo: 'foo'}

const map = new Map();
map.set('foo', 'foo');
console.log(map);        // {'foo' => 'foo'}
```

**Comment by joshghent** [comment]
@nickinnon Again great spot, I think there is no reason not to do this. @asiyani Have any thoughts?

How would you like to tackle this issue @nickinnon?

**Comment by riyaz-ali** [comment]
@joshghent @nickinnon Not just that, the [current log capturing closure](https://github.com/esfiddle/esfiddle/blob/develop/src/views/iframe.html#L30-L57) also alter the default behaviour for `console.log()`, like if I do something like `console.log('Value: %o', { ... })`, this logs the literal value `Value: %o [object Object]` and not the expected `Value: { ... }`

**Comment by nickinnon** [comment]
@joshghent @riyaz-ali Was this always the case with the console, or is this a new bug? Might be as simple as refactoring the change where the bug was introduced?

If it is not a bug; a few ideas off the top of my head:
1. We can write logic to convert objects/maps to strings like we do with Arrays [here](https://github.com/esfiddle/esfiddle/blob/5b1c0c3920375f1f87e7ef0b0090773ee2e1f951/src/views/iframe.html#L42).
2. We can use an open source js console.
3. We could not [mutate](https://github.com/esfiddle/esfiddle/blob/develop/src/views/iframe.html#L31) `window.console`.

Option 1 seems like it would get messy. We would have to add a special case for Maps, Objects, Arrays, closures, and others as they are discovered. Also, logging structures like this without indentation seems kinda lame.

Option 2 – not sure if this fits with the project's ethos.

Option 3 – Would probably not be a bad idea to do this. Not even sure if this the the problem, however. The issue may persist in the UI, but may not affect the browser's console. But there might be a reason this was mutated? 

Any thoughts? I've barley touched the code base myself, so let me know if there are other ideas.

**Comment by joshghent** [comment]
@nickinnon @riyaz-ali Sorry for the late reply here guys.

I think option 2 sounds the cleanest. If you have any thoughts on what console we should go for, then please let me know. If you find one you like, go ahead and implement it! This task is up for grabs and would greatly improve the site 💯

**Comment by joshghent** [comment]
@nickinnon Hey there, I kind of let this issue drift but wanted to check in to see if you were doing ok with your PR and this issue? Can I or anyone else in the team help? Contact me on gitter if you need any assistance! 👍 

If you no longer have time to work on it, that's fine too. We appreciate people generously donate their precious free time to this!

**Comment by nickinnon** [comment]
Hey there, 

Anyone looking at this issue – feel free to pick it up.

There are a few obligations I am currently tied to at the moment.

**Comment by joshghent** [comment]
@nickinnon I'm going to close this off for now as we are doing a massive rewrite to React and will be using a new console.
You can check it out on the react-redesign branch. Thank you for offering to help - hope to see you soon!
