### ISSUE TITLE
Add ES8 examples

### ISSUE THREAD

**Issue by ageddesi** [esfiddle/esfiddle#177]
#### Type of issue
- [ ] Bug
- [X] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Now that the ES8 line up is more set in stone we could start adding them in :)

**Comment by ageddesi** [comment]
Here is a great list of examples. 

https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66

**Comment by joshghent** [comment]
@ageddesi Yes brilliant idea! This was on my radar but if you had time then we'd greatly appreciate the help in adding these quickly! 👍

**Comment by jigar1101** [comment]
@ageddesi Just a suggestion, if we can automate some features of this by using just having a configuration in place from where we want the demo examples to be used. 
Something from [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_Next_support_in_Mozilla) can be use where each of its new feature has a demo [eg.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors) which we can use as an example.

This will ensure that the new versions in future require very few manual intervention like configuration addition of the links of these examples.

Let me know what you'll think about this? @joshghent @ageddesi

**Comment by joshghent** [comment]
@jigar1101 100% agree with this. Absolutely great idea.
I think for now we should get some manual examples for ES8 and then hopefully by the time ES9 roles around we will have this feature in. If someone wants to start working on this feature then I'd be happy to help! 👍

**Comment by jigar1101** [comment]
@joshghent Cool, I have created a different [issue](#190 ) for this automation feature.
This issue can be used to add es8 examples manually.

**Comment by joshuacrass** [comment]
@joshghent, I noticed that you already have a PR for this issue but I'd love to take this from you and add a bit more. It would be my first PR for an open source project. BTW I already forked it and started to work on it. You can check it out (feature/es8-examples) and let me know.
