### ISSUE TITLE
New Design For Example Dropdown

### ISSUE THREAD

**Issue by ageddesi** [esfiddle/esfiddle#186]
#### Type of issue
- [ ] Bug
- [X] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
With the growth of this dropdown. we should maybe think about breaking it into 2 parts.
1. the version 
2. the example

**Current Image**
![screen shot 2018-02-15 at 10 58 40](https://user-images.githubusercontent.com/1301564/36253393-557ccc08-123f-11e8-9438-c47361df2a79.png)

**Comment by eylamm** [comment]
Hi, as a first time contributor I would be happy to take @ageddesi's suggestion as a small feature. Maybe split the current drop down list into two separate lists, something like this - 

![capture](https://user-images.githubusercontent.com/18346474/36632566-db46ce30-1990-11e8-8a07-900ceecb9ec6.PNG)


@joshghent Let me know what you think.

**Comment by joshghent** [comment]
@elyamm Thanks a lot for the idea, I'm happy to go ahead with this. We're going to do a little redesign of this UI but I'm pretty sure we'll have these examples here so yeah we'd love to have this as a contribution! 

Thank you! ESFiddle would not be possible without contributors like you! :tada:

**Comment by eylamm** [comment]
Great! I'll give it a try

**Comment by eylamm** [comment]
Hey, so I am working on the ES versions drop down list as mentioned above (#186), and merging the latest changes I saw @jigar1101's awesome pull request #174 regarding the loading of external libraries. 

So now the code section already has multiple selectors in it - 
![dev_](https://user-images.githubusercontent.com/18346474/37242373-fc730200-2470-11e8-95d5-22e5972cd972.png)


And adding the es-versions selector looks a bit much - 
![1](https://user-images.githubusercontent.com/18346474/37242610-5284a208-2475-11e8-9f9b-3dcbc00f1f57.PNG)
doesn't it?

I thought maybe placing the library loader inside the settings menu, something like this -
![3](https://user-images.githubusercontent.com/18346474/37242613-5584ef44-2475-11e8-8f17-32d857dc7aaf.PNG)

Or should I just leave the es-versions selector for now?
@joshghent @jigar1101 Let me know what you guys think.

**Comment by jigar1101** [comment]
@eylamm Nice suggestion. 
We can move the dropdown in the settings menu as @joshghent was of the idea of moving it inside the settings modal once we have that implemented. 
There might be just one issue users might face related to discoverability of the dropdown. Any suggestions on how we can avoid that as the dropdown won't be discoverable unless the user clicks on the settings menu.

**Comment by eylamm** [comment]
@jigar1101 How about hinting the loaction of the loader in the libraries-list itself, instead of displaying 
the '-' place holder. So untill the user selects a library to load, it will see -

![default](https://user-images.githubusercontent.com/18346474/37251531-7793150c-251a-11e8-9db3-77052d58308d.png)

**Comment by jigar1101** [comment]
Yes this works @eylamm
@joshghent what do you think?

**Comment by joshghent** [comment]
@eylamm @jigar1101 I think once we rejig where all the buttons are it will make more sense. Settings looks out of place at the moment since it is outside of the editor frame. I'm against having text on the page because it makes it look unsightly and frankly the UI should be intuitive enough not to have to do things like this.

Let's wireframe out a new UI because I want to rewrite the app in React components. If anyone has any ideas then feel free to chip in 👍

**Comment by ageddesi** [comment]
I would love to reopen this as a design change is definatly needed.

**Comment by jigar1101** [comment]
@ageddesi That would be great! 👍

**Comment by jigar1101** [comment]
@joshghent Would love to be a part of the backend work! Couldn't find the details on it.
Can you let me know if its a different repository or any other branch?

**Comment by joshghent** [comment]
@jigar1101 repo can be found here https://github.com/esfiddle/api

Not made a huge start to it, will be fleshing out the swagger docs so we can build around that this weekend.

There is an issue in that repo that lists the routes that need to be made. If you want to tackle any then by all means please do! And ask in that repo or pm me on Gitter if you have any issues
