### ISSUE TITLE
Login not working?

### ISSUE THREAD

**Issue by preyneyv** [esfiddle/esfiddle#198]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
The login button takes me to GitHub, where I authorize the app. But then, this happens:
![image](https://user-images.githubusercontent.com/13533898/39698462-80a010da-5212-11e8-8635-a690481d23d9.png)

**Comment by joshghent** [comment]
Hmm, just checked the login and it works (sort of) but doesn't change the main bar to say Logout, so the site isn't saving the session. I'll have to investigate why. Thanks for pointing this out. Clearly stuff has fallen through the cracks this release!
