### ISSUE TITLE
Async and await example seems to be broken.

### ISSUE THREAD

**Issue by preyneyv** [esfiddle/esfiddle#199]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
The async/await example throws `ReferenceError: regeneratorRuntime is not defined`.
![screen shot 2018-05-07 at 9 24 49 pm](https://user-images.githubusercontent.com/13533898/39711338-18a74f86-523d-11e8-84cb-b49c62a7d61b.png)

**Comment by joshghent** [comment]
Hi @preyneyv, Yes I noticed this the other day. Thanks for pointing this out.

Is this something you would like to handle? I may not have time in the coming weeks as I have had an operation on my wrist (in fact I'm dictating this! 😄)

**Comment by OkuboTV** [comment]
Hello, if this issue is still open, I would like to make a contribution!

**Comment by joshghent** [comment]
@okubotv We'd love if you could have a crack at this! That would be fantastic!
