### ISSUE TITLE
"Star" fiddles

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#2]
So the idea here is that other people will be able to "Star" your fiddles. The most starred fiddles will then be displayed on a page like a hall of fame type thing but this will be added in the future.

The first job is to add a route for '/star/:fiddleID' which will save a star against that fiddle.
The second task for this PR is to add a Star button on the fiddle page (only when it is saved!) that will make a call to this route.

The rest will be handling in future issues and PR's, let's just get the functionality in place first.

**Comment by ageddesi** [comment]
Maybe you should consider braking this task down further for example.

* add api calls
* add stars to the page
* create a hall of fame page

**Comment by joshghent** [comment]
@ageddesi Done, yeah it was a quite a big task so I've said to just add the functionality to begin with and then we can proceed from there.

**Comment by ageddesi** [comment]
@joshghent I would like to give this a go over the weekend :) ⭐️

**Comment by joshghent** [comment]
@ageddesi All yours my friend 👍

**Comment by ageddesi** [comment]
How do we envision this implementation. 
Are we imagining that anybody can star a fiddle. (how do we define a user, ip etc)
Then do we have a tally against a fiddle for the amount of stars it has...

**Comment by joshghent** [comment]
@ageddesi Very good questions. Looking back at this, I think we maybe need to postpone it until we have a login for users (via github). Then when someone tries to star a fiddle it will ask them to sign in with github. I will make a new issue to add a github signin.

Unless you have any ideas on how we can make this work? I am very open to suggestions

**Comment by ageddesi** [comment]
I think allowing users to login before Staring fiddles is a good idea also allows us to do a lot more in terms of private fiddles etc.

**Comment by ageddesi** [comment]
Do we want a fiddle shows how many stars it has? and this will go up when you click on it to star it?

**Comment by asiyani** [comment]
Ya I think it's a good idea, in user model I have added field where we  can store fiddle no..
We need to create field in fiddle model to increament no of starts.... I forgot to do this :)

**Comment by ageddesi** [comment]
I will do that as part of the work for this so no need to worry.

**Comment by joshghent** [comment]
@ageddesi The github signin has now been done (thanks @asiyani). Let me know if you are still able to do this! We are very keen to add this feature.

**Comment by ageddesi** [comment]
I still would like to do this but have no free time now until next weekend. If someone wants to pick up in the meantime that is cool with me, otherwise I will pick it back up after.

**Comment by joshghent** [comment]
@ageddesi Hey did you get round to this at all? No problem if not 😀

**Comment by ageddesi** [comment]
Sorry I did not not I was also hit with the flu this week and still not recovered :( I am still happy for someone else to pick this up in the meantime.

**Comment by asiyani** [comment]
HI I am working on this one at the moment...

**Comment by joshghent** [comment]
@asiyani Brilliant, thanks dude.
@ageddesi 🤒 Ah that sucks dude! Hope you've recovered from the flu! Get better soon! 👍
