### ISSUE TITLE
Loading libraries from CDNJS

### ISSUE THREAD

**Issue by preyneyv** [esfiddle/esfiddle#201]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
I was thinking that we could allow users to load libraries from CDNJS, rather than self hosting and limiting which ones they can use. Thoughts?

**Comment by preyneyv** [comment]
Whoops, my mistake. We aren't self-hosting. But still, if users could pull in a library of their choice, I think that would be a good addition.

**Comment by joshghent** [comment]
@preyneyv Yes we definitely want to do this, thank you for the suggestion. We were planning on doing this along with a redesign - (basically moving fiddle settings into a tabbed modal dialog - like on Codepen for example). 

If this is something you'd like to handle, then go for it! We'd love to have you on board.

**Comment by preyneyv** [comment]
@joshghent Speaking of a redesign, can you please checkout #102?
