### ISSUE TITLE
How is this different from JSFiddle/CodePen/repl.it?

### ISSUE THREAD

**Issue by preyneyv** [esfiddle/esfiddle#202]
#### Type of issue
- [ ] Bug
- [ ] Idea/Suggestion
- [x] Question

#### How is this different from JSFiddle/CodePen?
Wanted to just raise this question, because I've explored CodePen and JSFiddle. I want to understand how this project is different. As I understand it, this will allow users to try out ES6, 7 and 8 stuff, and possibly more in the future. However, on CodePen, you can set the language to `JavaScript (Babel)` and achieve the same thing. Similarly, on JSFiddle, you can set the language to `Babel + JSX` to support ES6-8.

As I understand it, 2 key differences are present: 
- ESFiddle has examples to explain and demo ES6 syntax.
- ESFiddle has a console (not present in JSFiddle)

But the third candidate, repl.it, has all of these for multiple languages. And they support ES6 syntax as a separate language, `ES6`. Here's a [link](https://www.repl.it/languages/babel). So what makes this project different?

_P.S. Sorry to be the Devil's advocate here, but I think these are issues worth considering._

**Comment by joshghent** [comment]
Hi @preyneyv, No worries on playing devils advocate, I have considered this question much myself.
In all honesty, this project was created before widespread adoption of babel. Previously it was only really available if you spun up a page yourself. 

Now we are in a world where it is widely used, I wanted to transition ESFiddle into more of an educational tool by providing rich examples and content to help people learn new releases of ECMAScript. Not only showing them the new features, but also what they replace and why they have been introduced. I have yet to implement this educational content and am looking actively for someone to head this project up and give it some love.

The other main feature of ESFiddle - again, yet to be implemented - is to rewrite the site as an SPA that is offline-first. This goes along with other features to improve usage for presentations (embed functions, export code screenshots, adding download features). Additionally, along the educational line, we'd like to introduce class room features and live pair programming features. Again these have not been started or thought about but want doing.

We also would like to include features to check compare performance (like on JSPerf - only with less pirates) and somehow integrate something like Synk to check the security of code on the fly.

Overall, this project is not dissimilar to others. In the same way JSFiddle is not dissimilar to Codepen. But we are entirely open source and aim to encourage new contributors to help. We aren't looking to turn a profit (I currently just bear all expenses for the site - around £90 a year) - just to encourage new people to code and create something cool in the process.

If you'd like to help me in this endevour or have any further ideas on where *you* think the site should go, then please get in touch with me (my personal email is me@joshghent.com).

Thanks for asking this question 👍

**Comment by preyneyv** [comment]
Thank you sooo much for clearing that up. I was worried that this project would become redundant, which would be a shame. That list of new features sounds interesting, can we put them on a todo list? I am certainly interested in helping this project develop, and I'm glad that my help is also wanted, since this is my first time contributing to another person's project. I'm up for doing any tasks that need doing, but I'm going into 11th grade now so my turnaround time may be a bit slower.

**Comment by joshghent** [comment]
Yeah, I will have to raise them all as issues but I want to get the rewrite done first. I think we need to start a clean branch called 'rewrite' which we can then merge back into the master and develop branches. If you want you can kick that off? I will discuss that with you on the redesign issue however.

Yes no problem on the time, all our volunteers do this lovingly in their spare time and we encourage people to be with their family and friends first. Code can come later 👍 Thank you for your spirit to help. I will add you to the organisation.

**Comment by preyneyv** [comment]
Cool, let's kick off the rewrite. I'm thinking that we should start fresh, with none of the old code. We can pull in old code where necessary, of course, but I think a full rewrite is due, especially with all these new features. With that in mind, I'm creating a new branch called `rewrite`.

**Comment by preyneyv** [comment]
Actually, strike that, let's make incremental changes. Still making the new branch though.
