### ISSUE TITLE
Better UI/UX 

### ISSUE THREAD

**Issue by tarang9211** [esfiddle/esfiddle#21]
Could we improve the design of the site as a whole? It seems to plain for something as modern as ES6

**Comment by joshghent** [comment]
@tarang9211 I had this down on my list todo. 
I was thinking of making the code area and console fill the screen and allow resizing of them.

Do you have any suggestions?

**Comment by tarang9211** [comment]
Have you had a look at [Semantic-UI?](http://semantic-ui.com/introduction/getting-started.html) 

It's pretty good our of the box. Also, how do I become a Member on this repo?

**Comment by joshghent** [comment]
@tarang9211 Yeah that looks pretty good, that or bootstrap really but in both cases they might be overkill. I think we should also be looking at changing the color scheme.

If you become a regular contributor then I will add you as a member of the organisation.

**Comment by tarang9211** [comment]
Can we speak on gitter?

**Comment by joshghent** [comment]
@tarang9211 Yes I'm on there now. I will reply when I can.

If it is a longer message you want to send or discuss then perhaps email me :)

**Comment by ageddesi** [comment]
I agree with @joshghent that adding a UI framework may be overkill considering the simplicity of what the site offers. 
Also, it will keep the site size down which is always an extra win.

**Comment by tarang9211** [comment]
That's fine. Let's come up with a few ideas and I'll start a PR and get
suggestions from you guys. Sound like a  plan?

**Comment by joshghent** [comment]
@ageddesi [There already is one!](https://gitter.im/esfiddle/Lobby)

@tarang9211 Yeah sounds good, perhaps make some mockups in Photoshop or something so we can get an idea of what we are working towards.

**Comment by tarang9211** [comment]
Uhhh I hate to say this, but I don't have photoshop. I just kind of go with
HTML and CSS

**Comment by joshghent** [comment]
@tarang9211 That's fine! Just a screenshot of what you're working on would be good so we can improve on it 👍

**Comment by joshghent** [comment]
Going to close this off for now. I have a good idea of what needs doing and I will be working on raising issues and cracking away at them over the next few weeks. I want to break down this task into many issues so different contributors can work on them.
