### ISSUE TITLE
Changing from dark mode back to light mode editor stays dark

### ISSUE THREAD

**Issue by Sensational-Code** [esfiddle/esfiddle#217]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
If you change to dark mode then back to light mode, the theme for the editor will stay as monokai, leaving the editor dark. I believe when switching back to light mode the theme should switch back to default.
I would love to work this issue!

This appears to be a bug in the code directly, but to follow the issue guide:
Link to page: https://esfiddle.net/
I am on Chrome 67.0.3396.99 on Mac OSX High Sierra
Steps to reproduce:
1. Open main page
2. Switch to dark theme
3. Switch to light theme
<img width="1420" alt="esfiddle screenshot dark-light theme bug" src="https://user-images.githubusercontent.com/40759683/42163581-0d6c4fd0-7db8-11e8-87f8-90a3992fa116.png">

**Comment by romcar** [comment]
Hello there,

Is there a way for me to place a debugger statement and follow the flow of the code. I am trying to tackle this problem and feel like that issue may lie within the clickEvent.js. When I place the debugger statement (or breakpoints) in the code execution continues in chrome and does not pause so I can step through. Any advice is appreciated, thanks :D
