### ISSUE TITLE
ES7 code is not linted correctly

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#23]
When clicking the lint button on some code that contains ES7 features, such as Array.include() the code linter brings back a bunch of errors.

The linting is done by JSHint. I notice that we are a couple of version behind with this tool so updating it might fix it. However I would recommend when doing this we add JShint to be a served from a CDN as a deferred or async script.

**Comment by jinmehta13** [comment]
Hi, I'm looking to make my first open source contribution and this looks like a good opportunity. Could you provide some more specifics on how you would like to incorporate JShint as a CDN? Also, just doing some quick checks I only noticed the linter returning errors for "Map" and "Exponentiation Operator" not "Array Includes". Those errors persisted even after I substituted a JShint v2.9.4 file in place of the existing jshint.js under esfiddle/static/lib/jshint which was JShint v2.5.10. Looking forward to contributing. Thanks

**Comment by joshghent** [comment]
@jinmehta13 Hi there, thanks for looking into this. I looked into it briefly myself and since JSHint gets uglified into es6-fiddle.js then we do not need to replace it with a CDN.

Hmm that is odd that it doesn't fix it. Perhaps take a look into the specific linting errors and see if you can step through the JSHint code to try and spot the issue. It's more than likely a bug our end rather than JSHint.

**Comment by jinmehta13** [comment]
I think some of these ES7 features just aren't available in JSHint yet. I tried putting the code under the examples section of the Mozilla documentation for the [exponentiation operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation_(**)) directly into [JSHint](http://jshint.com/) and the errors/warnings still show. The Mozilla documentation example code for Array includes passes just fine though.

**Comment by joshghent** [comment]
@jinmehta13 Hmm ok, thank you for your research. Perhaps we can switch to something like Babel or Traceur to lint the code instead? Would you be able to do a PR for this?

**Comment by jinmehta13** [comment]
Sure thing, I'll give it a go. I checked out [Traceur](https://google.github.io/traceur-compiler/demo/repl.html#2%20**%203%20%2F%2F%208%0A3%20**%202%20%2F%2F%209%0A3%20**%202.5%20%2F%2F%2015.588457268119896%0A10%20**%20-1%20%2F%2F%200.1%0ANaN%20**%202%20%2F%2F%20NaN%0A%0A2%20**%203%20**%202%20%2F%2F%20512%0A2%20**%20(3%20**%202)%20%2F%2F%20512%0A(2%20**%203)%20**%202%20%2F%2F%2064) and it has the same errors/warnings as JSHint but Babel has support for things like the exponentiation operator so I'll switch to that. If I run into any trouble or have questions, I'll let you know!

**Comment by jinmehta13** [comment]
@joshghent I'm at a bit of a roadblock. So it looks like there's some Babel already in the project. Is that sufficient to make the switch? I tried using grunt-babel and added a .babelrc file with presets but I'm not sure how to replace JSHint with Babel in es6-fiddle.js. Can you point me in the right direction?

**Comment by joshghent** [comment]
@jinmehta13 yes Babel is used currently for the actual transpiling of the code and running it. JSHint is used for the linting.

This change would involve you looking for the Babel API methods to lint code. I can clear up JSHint but we need to make sure that babel is the one doing the transpiling and linting. Thanks :+1:

**Comment by tarang9211** [comment]
I thought eslint (my pr) was doing the linting?

**Comment by joshghent** [comment]
@tarang9211 That is the linting of the source code. We are talking about the linting on the actual site. When you click the lint code button 😁 Lots of linting 😆

**Comment by jinmehta13** [comment]
@joshghent, really hitting a brick wall here. I get that I need to replace the linting button code in es6-fiddle.js lines 233-269 with babel linting methods but I'm finding very little documentation for inline linting with babel or babel-eslint. Everything seems to be directed at linting a file or directory.

**Comment by SaraVieira** [comment]
I think this is a matter of updating jsHint from what I have tested, maybe include it as a node module and get it from there instead of from the libs
