### ISSUE TITLE
Focus Outline Invisible On Footer

### ISSUE THREAD

**Issue by mrAl-x** [esfiddle/esfiddle#234]
#### Type of issue
- [X] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description
The focus `:outline` is the same color as the footer background which makes it invisible when focusing the footer links. In the screenshot you can compare the footer color with the outline's

<img width="408" alt="screenshot 2018-10-08 at 20 41 42" src="https://user-images.githubusercontent.com/4906508/46630058-e9737600-cb3a-11e8-9edf-10eb9f264ab2.png">

**Comment by joshghent** [comment]
Completed in #235 ! Thanks @mrAl-x
