### ISSUE TITLE
Create editor pages in React

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#238]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
We need to re-create the existing editor with a new design (in line with the homepage) in the `react-redesign` branch. This will be the most used part of the app so take time to implement it.
Currently, because the API is not written we are just working on the front-end and will have no saving etc. Allow space where we can hit our API endpoints however to get and save fiddle data etc.

**Comment by rahulnpadalkar** [comment]
I am interested in contributing. How can we move forward?

**Comment by joshghent** [comment]
@rahulnpadalkar There is already an active PR here, but feel free to create the About page for us here https://github.com/esfiddle/esfiddle/issues/242 👍 We would appreciate your contribution
