### ISSUE TITLE
Dark/Light mode switch doesn't update theme dropdown element

### ISSUE THREAD

**Issue by Sensational-Code** [esfiddle/esfiddle#246]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description
If you change to dark mode then back to light mode, the theme will change but the theme dropdown will stay as monokai when it should update to default.

Steps to reproduce:

1. Open main page
2. Switch to dark theme
3. Switch to light theme

![theme not changing](https://user-images.githubusercontent.com/40759683/47603985-76765600-d9a8-11e8-8fb9-ff0e1e4abcb6.gif)

**Comment by joshghent** [comment]
@Sensational-Code Thank you for both reporting and fixing this issue! Great work

**Comment by Sensational-Code** [comment]
@joshghent No problem, happy to help!
