### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#25]
Ok so it's high time we got a logo!
This does not have to be the next coca-cola or nike but it would be nice to have a logo of some description.

This logo would be used as an avatar for the project on github and on the website so we would need a logo that can fit in a square.

We have an established maroon color scheme but this is open to change. Go wild!

**Comment by MorrisB--** [comment]
Hello, I'm wondering if I can design the logo for you guys and hopefully join the team. Please let me know if you have any specific dimensions or anything like that.

Thank you,
Morris

**Comment by joshghent** [comment]
@MorrisB-- No specific dimensions we just need something that will fit in a square well (like an avatar). It would be good if we had an avatar image and then more of a header image. For example Facebook have the ['F' logo](https://facebookbrand.com/wp-content/themes/fb-branding/prj-fb-branding/assets/images/fb-art.png) and then a [full 'Facebook' logo](https://www.seeklogo.net/wp-content/uploads/2015/07/new-facebook-logo-2015-400x400.png)

**Comment by MorrisB--** [comment]
Sounds good, I'll have a mock up early next week, thanks!

**Comment by MorrisB--** [comment]
@joshghent One quick question, should the case for the text look like 'esfiddle' or 'ESFiddle'?

**Comment by joshghent** [comment]
@MorrisB-- I think ESFiddle since the ES stands for EcmaScript

**Comment by MorrisB--** [comment]
![esfiddle_dd63a01b](https://cloud.githubusercontent.com/assets/8133610/22357551/8ae12490-e3fe-11e6-9e03-cb0e2b921e6d.jpg)
![esfiddle_dd63a01a](https://cloud.githubusercontent.com/assets/8133610/22357554/9195bbde-e3fe-11e6-986b-a41b301a3854.jpg)

Feel free to rip it apart and let me know what you think.

**Comment by joshghent** [comment]
@MorrisB-- Sorry for the late reply.

I like the Square logo but not sure a fan of the code icon on the E. How about something like the "JS" unofficial logo

https://camo.githubusercontent.com/eb464a60a4a47f8b600aa71bfbc6aff3fe5c5392/68747470733a2f2f7261772e6769746875622e636f6d2f766f6f646f6f74696b69676f642f6c6f676f2e6a732f6d61737465722f6a732e706e67

**Comment by MorrisB--** [comment]
@joshghent I like the using an actual fiddle idea that would be pretty sweet! I'll have a revised version soon, thanks!

**Comment by joshghent** [comment]
@MorrisB-- Hey, how's it going? Need any help?

**Comment by MorrisB--** [comment]
@joshghent Yeah I'm still working on it, got a little side tracked, I'll be working on it full throttle this weekend!

**Comment by uzluisf** [comment]
@joshghent I took a go in the logo design!  

1) 
![rounded_logo](https://cloud.githubusercontent.com/assets/22332927/23176717/4edcdf6e-f832-11e6-9f63-f6405da51a4f.png)

2)
![rounded_logo_only](https://cloud.githubusercontent.com/assets/22332927/23176735/5f6e1bc2-f832-11e6-83d3-6830b42944e2.png)

3)
![long_logo_may](https://cloud.githubusercontent.com/assets/22332927/23176736/6518423c-f832-11e6-94ba-487c3017d90b.png)

4)
![long_logo_min](https://cloud.githubusercontent.com/assets/22332927/23177025/60c69fde-f833-11e6-86c6-62366f4d123d.png)

**Comment by MorrisB--** [comment]
@uzluisf Those look pretty sweet, mine ended up looking liike this
![esfiddle_dd63a02a](https://cloud.githubusercontent.com/assets/8133610/23186803/0466686c-f84e-11e6-8d41-c53d72754b16.jpg)
![esfiddle_dd63a01b](https://cloud.githubusercontent.com/assets/8133610/23186804/046b30ae-f84e-11e6-9be4-2a4d320b089c.jpg)

**Comment by ageddesi** [comment]
maybe the fiddle could be the I in fiddle ?

**Comment by SaraVieira** [comment]
Great work @MorrisB ! I really like both those ones 👍

**Comment by uzluisf** [comment]
@MorrisB-- Yours look great too! What's the font you're using?

**Comment by MorrisB--** [comment]
@ageddesi I was trying the i, and both of the d's it just didn't work out lol 

@SaraVieira @uzluisf Thanks! I don't remember what font it is I pretty much just searched Facebook font

**Comment by joshghent** [comment]
@MorrisB-- I like the 2nd version. I won't close this issue off just yet as I know @SaraVieira is working on the redesign of the site atm and that might include changing the colors we use. If we do change then it may require a slight tweak changing the color but I'm happy to use those logos 👍 
Thanks a lot!

**Comment by tarang9211** [comment]
just pitching my two cents in. I really like all the logos, but I do think they are a little too complicated and intricate. I say this when I compare this to the logos of StackOverflow, JsFiddle, even CodePen. I like @MorrisB-- second logo (from his latest comment). just my two cents guys, I'm a fan of simplistic logos which are easy to remember. 

For example - when a user sees the logo he should be able to recollect and say "Oh this is from the ESFiddle website"

**Comment by SaraVieira** [comment]
Hello @tarang9211, 

That is a valid statment, what you are saying is that you would prefer something like this:
<img width="841" alt="screen shot 2017-02-23 at 10 21 33" src="https://cloud.githubusercontent.com/assets/1051509/23255038/fa3fd6f6-f9b1-11e6-95b1-bd77b684afe5.png">

over big logos right ?

**Comment by tarang9211** [comment]
Yes! It's simplistic and easy to remember. Let's try out more variations?

**Comment by SaraVieira** [comment]
Does anyone have sketch ? I can provide the .sketch file for this

I'll upload more variations later tonight @tarang9211  👍

**Comment by tarang9211** [comment]
Also, let's take this discussion to Gitter!

**Comment by tarang9211** [comment]
I do have sketch @SaraVieira

**Comment by SaraVieira** [comment]
@tarang9211 You can play with it if you want, here is the sketch file:
[esfiddle.zip](https://github.com/esfiddle/esfiddle/files/796211/esfiddle.zip)

**Comment by joshghent** [comment]
@SaraVieira That's the best suggestion so far. Looks good.

I think we shouldn't do the whole fiddle thing as it seems a little forced and doesn't fit with the typography we have. 

I think instead we should have some lab goggles side on or perhaps head on above the esfiddle logo. This will represent the experimentation aspect of ESFiddle as well as the educational side to it.

**Comment by SaraVieira** [comment]
<img width="818" alt="screen shot 2017-02-23 at 11 05 00" src="https://cloud.githubusercontent.com/assets/1051509/23256582/f33bb11c-f9b7-11e6-9e9c-5cbea6d4a5b9.png">

Like this ? @joshghent

**Comment by SaraVieira** [comment]
I think this actually looks awesome ! 👯

**Comment by tarang9211** [comment]
Still a fan of the first one @SaraVieira

**Comment by SaraVieira** [comment]
@tarang9211 you liked it better than the last one ?

**Comment by tarang9211** [comment]
@SaraVieira Yup. I find the second one too complicated.

**Comment by SaraVieira** [comment]
@tarang9211 maybe removing some of the glow in the glasses and the lettering would help

**Comment by tarang9211** [comment]
Maybe, I think the learning will happen on the site itself. What we need to do is get a logo simple enough for anyone to remember. 

Example : When someone sees the logo, they should be like oh yeah, that's ESFiddle!

**Comment by SaraVieira** [comment]
<img width="644" alt="screen shot 2017-02-23 at 11 11 59" src="https://cloud.githubusercontent.com/assets/1051509/23256797/ea5229a4-f9b8-11e6-9cc4-7e72f586aa12.png">

Shadows and lettering removed

**Comment by joshghent** [comment]
@SaraVieira Looks good. Perhaps remove the hexagon as I think it makes it look more polar 😁  I think it looks good. Add the letter back too! I think perhaps a slightly thicker font however. Play around with the type faces I reckon.

**Comment by SaraVieira** [comment]
@joshghent Remove the haxagon and place what ? That was my issue :/

**Comment by SaraVieira** [comment]
<img width="547" alt="screen shot 2017-02-23 at 11 35 01" src="https://cloud.githubusercontent.com/assets/1051509/23257521/23b41ba0-f9bc-11e6-9d05-afcfd68490cd.png">

**Comment by tarang9211** [comment]
I like this, but I don't understand the goggles.

**Comment by SaraVieira** [comment]
Because science and learning 💃

**Comment by tarang9211** [comment]
Agreed, but we're not promoting a "science" application. Hope I'm not being too demanding/negative.

**Comment by SaraVieira** [comment]
But a learning one and I think it amounts to the same in the end of the day, if we followed the computer route we would have a terminal logo just like every other programming website

**Comment by joshghent** [comment]
@tarang9211 As I said when I suggested this idea, the goggles perhaps suggest the experimentation side of the site as well as the education that people will get by using our code examples.

@SaraVieira is exactly right. My idea was to have something that is a symbol for the site that is away from just uninventive code type logos. For example Yarn pkg uses a cat.

**Comment by SaraVieira** [comment]
@joshghent Should we vote on the logo ?

**Comment by SaraVieira** [comment]
<img width="428" alt="screen shot 2017-02-23 at 11 49 09" src="https://cloud.githubusercontent.com/assets/1051509/23258002/1de04b70-f9be-11e6-882a-1caafce0d0e2.png">

<img width="378" alt="screen shot 2017-02-23 at 11 50 50" src="https://cloud.githubusercontent.com/assets/1051509/23258042/61015ffc-f9be-11e6-8c16-f26f0eb43180.png">

**Comment by joshghent** [comment]
@SaraVieira Looks good. I think the font needs changing to something different. I'm not against a script/writing type font but I'm not a fan of that one (Lobster I think?)

**Comment by SaraVieira** [comment]
@joshghent but do you prefer just the googles or the googles with the text ? I like the previous to these ones better

**Comment by joshghent** [comment]
I prefer the goggles with the text underneath.
It will act as the big logo with the text
And then for the icon we will just use the goggles.

**Comment by SaraVieira** [comment]
Cool then,  I will some variations with fonts later when I get off work :)

**Comment by joshghent** [comment]
@SaraVieira Looking at it again, I reckon the shine on the glasses would be good too.

**Comment by SaraVieira** [comment]
<img width="484" alt="screen shot 2017-02-23 at 17 27 16" src="https://cloud.githubusercontent.com/assets/1051509/23270936/7fba1f22-f9ed-11e6-8bae-7548fc30b6cf.png">


Like this ?

**Comment by joshghent** [comment]
@SaraVieira Yeah exactly, now I guess to have a play around with font faces. Not sure what style of font to go for even. Any ideas?

**Comment by SaraVieira** [comment]
<img width="386" alt="screen shot 2017-02-23 at 18 03 36" src="https://cloud.githubusercontent.com/assets/1051509/23272296/967eb9a2-f9f2-11e6-8f30-23e2a5b666d5.png">

This one uses bree serif

**Comment by SaraVieira** [comment]
This one is more playful:

<img width="403" alt="screen shot 2017-02-23 at 18 05 34" src="https://cloud.githubusercontent.com/assets/1051509/23272322/b5874e22-f9f2-11e6-817a-ee50e7966ad2.png">

**Comment by SaraVieira** [comment]
@joshghent Can you give some idea of fonts from here: https://fonts.google.com/ ?

**Comment by joshghent** [comment]
@SaraVieira Just had a look and found these similar alternatives
https://fonts.google.com/specimen/Raleway
https://fonts.google.com/specimen/PT+Sans
https://fonts.google.com/specimen/Montserrat

**Comment by SaraVieira** [comment]
Raleway
<img width="475" alt="screen shot 2017-02-23 at 19 38 16" src="https://cloud.githubusercontent.com/assets/1051509/23275847/f0d63f62-f9ff-11e6-835f-6b7f2a06ba07.png">

PT Sans
<img width="380" alt="screen shot 2017-02-23 at 19 38 36" src="https://cloud.githubusercontent.com/assets/1051509/23275845/f0d2906a-f9ff-11e6-8f1d-92e2fd84b113.png">

Montserrat
<img width="425" alt="screen shot 2017-02-23 at 19 38 56" src="https://cloud.githubusercontent.com/assets/1051509/23275846/f0d2ffd2-f9ff-11e6-9237-d8ad97a94a8b.png">

The playfull one:
<img width="403" alt="screen shot 2017-02-23 at 18 05 34" src="https://cloud.githubusercontent.com/assets/1051509/23272322/b5874e22-f9f2-11e6-817a-ee50e7966ad2.png">

Bree Serif:
<img width="386" alt="screen shot 2017-02-23 at 18 03 36" src="https://cloud.githubusercontent.com/assets/1051509/23272296/967eb9a2-f9f2-11e6-8f30-23e2a5b666d5.png">

**Comment by SaraVieira** [comment]
I like PT Sans and Bree Serif, how about you @joshghent ?

**Comment by joshghent** [comment]
@SaraVieira Yeah PT Sans gets my vote. I'm happy to go with that if everyone else is.

**Comment by SaraVieira** [comment]
Black BG:
<img width="473" alt="screen shot 2017-02-23 at 19 45 08" src="https://cloud.githubusercontent.com/assets/1051509/23276038/a377d36a-fa00-11e6-9f57-6c2e2066950b.png">

Black BG with all lowercase letters:
<img width="546" alt="screen shot 2017-02-23 at 19 46 25" src="https://cloud.githubusercontent.com/assets/1051509/23276072/d07b0c1a-fa00-11e6-8d9c-d161e06ab796.png">

**Comment by MorrisB--** [comment]
@SaraVieira Sold on the black background!

**Comment by SaraVieira** [comment]
Awesome !

@joshghent Can this issue be closed ?

**Comment by SaraVieira** [comment]
Here is the ZIP with the sketch, SVG and PNG files 

[ESFiddle Logos.zip](https://github.com/esfiddle/esfiddle/files/799023/ESFiddle.Logos.zip)

**Comment by joshghent** [comment]
Ok going to close this issue off for now.
Thank you @MorrisB-- @uzluisf and @SaraVieira for your designs.
