### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#252]
# We are looking for a new maintainer

### What does this mean?
I do not now have time to properly dedicate to ESFiddle and think it would do much better with someone else taking the helm. I will still be around to contribute but day to day running will be down to you - the new maintainer! I will continue to pay for the server and domain.

### What's the status of the project?
The project as is gets a decent amount of monthly visitors (5k+) and has been featured in the book [youdontknowJS](https://github.com/getify/You-Dont-Know-JS). 
A number of months ago, I set about rewriting ESFiddle into a new React Frontend and Typescript Express backend and preserve the old data. The goal was to make the frontend more social and have featured and starred fiddles. In addition to this we were looking to expand the horizons of the app to include more educational content including examples and blog posts. We also had the goal of adding dynamic NPM module importing so people could really feel the power of Ecmascript within the browser.

### Do I have to carry on with that?
No you don't, if the new maintainer or maintainers decide they want to do a plain old JS backend and a VueJS frontend, that's absolutely fine with me. You are free to craft the app, however you see fit.

### Why keep the project? There is already TryBabel
Yes, this is true, and with the rise of other tools like Codepen, ESFiddle started to become less of a unique site. However, I believe there is still a market for a tool like this with educational content and pair programming features. Also there is the potential it can be used on other programming tutorial websites to create interactive courses. 

### Can there be more than one maintainer?
Yes, the more the merrier! I believe that collaboration is the best way to work and it saves one maintainer from having all the burden to bear.

### How do I apply?
Just post a comment below!

I can't wait to see what ESFiddle becomes and am immensely proud of how far it has come already.

**Comment by collinmesser** [comment]
I might be interested in this. Would you mind emailing me at collin@collinmesser.com?

**Comment by ghost** [comment]
I would also like to help out with this project. It's pretty cool! :)

**Comment by joshghent** [comment]
Hey @anagabriel42 - thanks for your interest in this. @collinmesser has made a bit of a plan with myself about the direction for ESFiddle already but I've just created a private gitter channel https://gitter.im/esfiddle/admins# so we can discuss things altogether.

It would be amazing to have another hand in helping build ESFiddle and another head full of ideas! I've added you to the GitHub organisation 👍

**Comment by rajmayank** [comment]
Hey @joshghent, I'd be up for the task.
I can help with not only the app itself but the infra as well. Few years ago when I used to work primarily on frontend, esfiddle was a goto. It'd be great to be able to contribute back to it.

**Comment by collinmesser** [comment]
Hey @rajmayank if you're up for it still I'll add you to the core team. I'm redesigning the site over here [https://github.com/esfiddle/site](https://github.com/esfiddle/site). Feel free to take a look and let me know if you have any questions. I'll add you to the gitter admin channel too.

**Comment by collinmesser** [comment]
Closing this for the time being. Please take a look at https://github.com/esfiddle/site if you're interested in contributing.

**Comment by rajmayank** [comment]
Hey @collinmesser, got the invites. Thanks for those.
I'm out right now for a conference. I'll start taking things up with you in a weeks time. In the mean time can you please also add me to Glitter, so that we can communicate over there.

**Comment by joshghent** [comment]
Reopening this issue as I'd love for some new maintainers to come help me out! I'm dedicating a bit more time to the project now so it can get back on it's feet.
As I see it, we've got a few pressing prioritized
- Swap to GH Actions and ship docker images (since we moved the hosting)
- Fix the embedded view

Going forward, I'd love to create a brand new homepage with example fiddles, recent (public) fiddles and integrate with Carbon.now.sh

Please ping me here on this issue if you're interested!

**Comment by patelg123** [comment]
Hi Josh, I hope you are well. I would love to get involved with this again. Let me know how I can help.

**Comment by joshghent** [comment]
@patelg123 Hi mate! Long time no see! There is tonnes to do to make it more mobile friendly. But the main things at the moment are to fix the embedded view of fiddles, bring it up to date so it contains examples of ES2019 code and making the profile page a bit sleeker (maybe more emojis). Have at it!

**Comment by patelg123** [comment]
@joshghent is this repository now being used for the site rather than https://github.com/esfiddle/site ?

**Comment by joshghent** [comment]
@patelg123 Yes, this repo is under active development again. Previously another maintainer went to rewrite the site into Vue and a new API in Express/Typescript. But I'm now just going to give this repo some love and hope other can too! Please see the issues tab for some features and fixes that need working on! There is loads to do so any contributions would be welcome.
