### ISSUE TITLE
New Code Examples! - On going project!

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#266]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
One of ESFiddle's great features is the code examples.
With new ECMAScript releases, we get new Javascript features and therefore new example code blocks to show off these new features!
This is a great first contribution for new programmers. Simply pick a new ECMAScript feature (from 2016 onwards) and write some example code for it, then add the file to `https://github.com/esfiddle/esfiddle/tree/develop/src/js/examples`

Then submit your Pull request! 🎉 If you need any help then comment below!

**Comment by Surajv311** [comment]
@joshghent  Sir, 
I have worked on this issue and made a PR. Could you please review it and let me know any shortcomings?

**Comment by Muskan0510** [comment]
Hi, I'd like to work on this!
