### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#27]
We should probably add an about page for the project.

The content will contain the following:
- About the project
- Information on how to report a bug
- Guide to contribute - link to the contribute guide
- Link to github project

A route will also need adding to the app.js file

**Comment by krys2fa** [comment]
Hello @joshghent, I would like to work on this. Could you please provide me with some more details?

**Comment by joshghent** [comment]
@krys2fa What kind of detail would you like?

The page should look similar to the fiddle page with the red bar at the top but other than that the design is pretty much free reign.

**Comment by joshghent** [comment]
@krys2fa Hey, how's it going?

**Comment by velascoDev** [comment]
Hello Josh, I would be happy to help with this.

**Comment by joshghent** [comment]
@velascoDev Yeah sure thing, all yours! 
Don't worry to much about the copy on the page, when you submit a PR I will go in and add stuff about the project if needed.
Thanks 😁

**Comment by joshghent** [comment]
Done in https://github.com/esfiddle/esfiddle/pull/50. Thanks @velascoDev!
