### ISSUE TITLE
Create github actions Docker pipeline

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#271]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Currently the app is deployed on docker on a digitalocean host I own.
To allow for updating this, please configure a pipeline that builds the docker image on the develop and master and scans it for vulnerabilities. It then needs to ship it to the github container registry

**Comment by jigar1101** [comment]
Hey, @joshghent Hope you're doing good! Sorry was away from this repository for quite along.

I can take this up if you're not working on it already. 
I can see you've already done some setup on Github Actions for docker, let me know is there anything I can contribute or be of help.

**Comment by joshghent** [comment]
Hi @jigar1101 - great to hear from you again bud! Don't worry nothing has really been going on - I'm starting to pick it up again.
Yes I've already started a bit of work on this but currently it just builds the image and sends it to the docker hub (or should), that needs tearing out and making it so it ships to the GitHub registry, it should also scan for vulnerabilities in the image and not exceed a certain size.

**Comment by jigar1101** [comment]
That's great @joshghent 
I'll pick up something else then.

**Comment by joshghent** [comment]
@jigar1101 No you're more than welcome to do this ticket, there is loads to do for it! I just shoved some boilerplate in that doesn't work 😆  PR's would be very welcome on this one!

**Comment by jigar1101** [comment]
@joshghent What is the value for `github.repository`? Is it `docker.pkg.github.com`?

**Comment by jigar1101** [comment]
@joshghent The reason your current dockerfile is failing is because, we need to login using the github token in the github registry before pushing.
Also, the image id would be `IMAGE_ID=${{ secrets.github.repository }}//$IMAGE_NAME`

I believe you would followed this URL - https://www.learncloudnative.com/blog/2020-02-20-github-action-build-push-docker-images/ ?
