### ISSUE TITLE
Resolve deprecated dependencies (multiple PR's welcome)

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#277]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Lots of the dependencies we use have now been deprecated and need updating or removing.
A successful PR for this issue will **resolve at least 1 of these** deprecated dependencies - we will therefore be accepting multiple PR's for this issue.

Please see the list of dependency warnings below:
![Screenshot 2020-07-30 at 10 04 51](https://user-images.githubusercontent.com/2934976/88903795-23e85e80-d24c-11ea-922a-b264ea0ece93.png)

**Comment by Patil2099** [comment]
@joshghent I would love to work on this issue.

**Comment by joshghent** [comment]
@Patil2099 go for it mate
