### ISSUE TITLE
Minify Javascript source

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#278]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Add a build step when building the docker image or building for production to minify the Javascript source to improve load times on the website. Currently Page speed insights says it takes 250ms for "blocking time" and that we could save 56ms by minifying the JS. Small savings but they add up!

**Comment by patelg123** [comment]
@joshghent Sorry if I am being thick, but isn't it a case of just adding the following to the uglify section of grunt.initConfig in the Gruntfile.js file?:

'dist/src/es6-fiddle.js': ['dist/src/es6-fiddle.js'],

**Comment by joshghent** [comment]
@patelg123 Yes could be! Take a look in your browser network tab to see if the source becomes minified for all JS content! Additionally, if you got to google's page speed insights and run it against esfiddle.net then you'll be able to see all the files that aren't minified 👍  Hope that helps :)

**Comment by patelg123** [comment]
@joshghent I've raised a pullrequest for this, please can you take a look when you get the chance.

**Comment by joshghent** [comment]
Resolved by #286
