### ISSUE TITLE
Update CONTRIBUTE.md

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#28]
The contribute guide needs some love. It has a setup guide and that is basically it.

We need to make sure that people run 'grunt test' before submitting a PR. Maybe this needs setting up as a git hook in the future.

Any other information to help new comers would be helpful. The guide needs to be as concise and streamlined as possible.

**Comment by krys2fa** [comment]
Hello @joshghent, I would like to work on this issue. Kindly provide me with further instructions. Thanks

**Comment by joshghent** [comment]
@krys2fa It needs to be a guide containing the following

- How to setup a local development environment, that is as easy as possible to follow, link to guide to get running with mongo and node etc.
- Show the process of how people can make changes and then submit PR's after they have made the changes.
- Make the point for people to run `grunt test` before submitting a PR.

If you have any other ideas then include them. I'm open to criticism here.

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/38

Thank you to @ageddesi for his second PR 🎉
