### ISSUE TITLE
ES7 -2017 - Async-await best practice example

### ISSUE THREAD

**Issue by AshifMohammad** [esfiddle/esfiddle#289]
#### Type of issue
- [ NA ] Bug
- [ Async-await with `.then` is an anti-pattern for the asynchronous behavior, rather we should make use of `try-catch-finally` pattern along with async- await feature, raising a PR against this Issue ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Async-await with `.then` is an anti-pattern for the asynchronous behavior, rather we should make use of `try-catch-finally` pattern along with async- await feature, raising a PR against this Issue
we have. right now in example.js/es8-async-await.js
/* 
  Await requires a Promise to be returned and
  can only be used inside an async function.
*/ 
async function getFood() {
  console.log('Blast off 🚀');

  cosnt await fetchMeat()
    .then((bacon) => {
      console.log(bacon);
    })
    .catch((err) => {
      console.error(err);
    });

essentially , if we combine async-await with `.then` then  we are moving towards the `then` pyramid , rather we should comply the `try-catch-finally` along `async-await` ?

**Comment by joshghent** [comment]
Hey there :wave: Thanks for filling an issue. Our maintainers will get looking into it shortly but in the meantime, have a go yourself. You can get setup with ESFiddle locally by following our Contribution guide.' first issue

**Comment by AshifMohammad** [comment]
@joshghent I  raised a PR against this change or suggestion - https://github.com/esfiddle/esfiddle/pull/290 
please take a look?
