### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#3]
Simples really. Add a dark theme.

Make it a option that is saved in localstorage like the theme or vertical/horizontal height settings.

The esfiddle maroon color can either change to something that contrasts well with the black or keep it the same. Experiment! 👩‍🔬

**Comment by NeptunianEclipse** [comment]
Hey @joshghent, I would like to have a go at this.

**Comment by joshghent** [comment]
@NeptunianEclipse All yours friend 👍

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/45

Thanks @NeptunianEclipse 👍
