### ISSUE TITLE
esfiddle.net website is not working 

### ISSUE THREAD

**Issue by Pranavtechie** [esfiddle/esfiddle#301]
#### Type of issue
- [ ] Bug

#### Description (include any screenshots or debugging information if applicable)
![image](https://user-images.githubusercontent.com/66348494/124108223-a6445880-da83-11eb-8482-2b0307a2d980.png)

**Comment by joshghent** [comment]
Hey there :wave: Thanks for filling an issue. Our maintainers will get looking into it shortly but in the meantime, have a go yourself. You can get setup with ESFiddle locally by following our Contribution guide.' first issue

**Comment by Pranavtechie** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/66348494/148668934-534bb315-f312-4446-b412-a3563ca48d27.png">

I guess you guys have to generate the SSL certficate

**Comment by joshghent** [comment]
I didn't renew the esfiddle.net domain as I didn't have time to maintain it anymore :)
I still have the old DB etc.
