### ISSUE TITLE
404 Fiddle not found

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#32]
When a fiddle is not found (by navigating to one that does not exist) then we need to display a 404 page rather than a json response that the fiddle has not been found.

A PR that addresses this issue would do the following
- Add a 404 page with text saying "Sorry the fiddle could not be found."
- Change the API to respond with a 404 error and send the user to the 404 page.

**Comment by abhishek71994** [comment]
I would like to work on this, I am just getting a hang of the backend part of a website. So if its okay, I'd like to give this one a go.

**Comment by joshghent** [comment]
@abhishek71994 Yeah sure 👍 Look forward to your first PR

**Comment by asiyani** [comment]
@joshghent I was thinking rather than displaying whole 404 page to cust we can just Display message on on screen console page "Sorry the fiddle could not be found.".

May be display fiddle Number(string) as well so eu can check if it's typed correctly. 

That will save a click for user to use back button and go to main website.

**Comment by joshghent** [comment]
@asiyani Yeah that sounds like a better idea. Better for UX certainly.
@abhishek71994 Do you still want to cover this issue?

**Comment by asiyani** [comment]
@abhishek71994  ya we need  server to send 404 status with message that includes fiddle ID as well.  
so basically we just need to change backend I dont think so we need to make any changes to the frontend. I might be wrong here didnt check front end code yet...

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/40
