### ISSUE TITLE
Rebasing?

### ISSUE THREAD

**Issue by tarang9211** [esfiddle/esfiddle#37]
What branch should we be rebasing against? Master or Develop?

**Comment by tarang9211** [comment]
I can `git fetch upstream`. I can't `git checkout master` and then create my branches from master. What's going on with this?

**Comment by joshghent** [comment]
All development should take place as a branch from "develop". All the PRs will be submitted there and then I will merge them back in master.

I'll look at updating the docs to improve this for clarity.
