### ISSUE TITLE
Add a blog

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#42]
This PR will need to add a blog to the site. There doesn't need to be a CMS behind it as I can manually add posts.

It needs to ideal have a similar structure to a jekyll blog with a folder of posts that the blog will then display. It does not need to have comment functionality unless it is built into a library that is with the blogging platform.

I would suggest using something like https://github.com/jsantell/poet

For this to work a item would need to be added to the navbar called 'Blog'. It would then need setting up with a route on the backend for '/blog'.

**Comment by tarang9211** [comment]
@joshghent Although I agree with this, don't you think we can use Medium? That site seems to be really popular for blogging!

**Comment by joshghent** [comment]
@tarang9211 Yeah, there might be a way to have the blog hosted on medium but with our own domain. Does google index those posts as our site or mediums? Do you know anything about this?

**Comment by cyberangle** [comment]
Why not just install wordpress onto your server?

**Comment by joshghent** [comment]
@cyberangle Its hosted on heroku. And I would prefer to just have something skinny that we can just have markdown files on. Not a bulky CMS that has a number of security holes

**Comment by galxzx** [comment]
Are you still looking for a lightweight blog to be added? I can do this.

**Comment by joshghent** [comment]
@galxzx I was trying to work on this today and found there was more to it than I initially thought!
If you are familiar with it or feel comfortable doing that, it would be fantastic 👍

**Comment by galxzx** [comment]
@joshghent How hands on can it be? With Hexo, you can fairly easily build static pages from markdown files in node. You would then have to manually add the static files generated by Hexo to the site after writing each post.  For multiple blog contributors, a separate repo would likely have to be set up to contain the Hexo files before generation so that each call to generate would spawn from the same files.

**Comment by joshghent** [comment]
@galxzx It's not difficult per say I was going to use poetjs and then use ejs templates for the blog posts. Having a static blog generator though is good too.
We would need a new route setting up called /blog (make sure you exclude this from the fiddles route too), and then just have it load all the articles with a preview and then you could click through to them. That's about it really.
Let me know if you're able to get started. This wasn't part of the original 2.0.0 but I'd like to get it released as soon as.

**Comment by galxzx** [comment]
@joshghent I'll get started on this today.

**Comment by SaraVieira** [comment]
I think @galxzx already closed this one 👍

**Comment by joshghent** [comment]
@SaraVieira Thanks for reminding me again! 😁 

Completed in https://github.com/esfiddle/esfiddle/pull/57
Thanks @galxzx 👍 🎉
