### ISSUE TITLE
feature: loading 3rd party javascript library

### ISSUE THREAD

**Issue by asiyani** [esfiddle/esfiddle#46]
User should be able to load 3rd party library and do some coding on that. 

e.g. 
User should be able to load lodash library and then run following fiddle to get response in console page.

```
var object = { 'a': { 'b': 2 } };
var other = _.create({ 'a': _.create({ 'b': 2 }) });
 
_.has(object, 'a');
// => true
 
_.has(object, 'a.b');
// => true
 
_.has(object, ['a', 'b']);
// => true
 
_.has(other, 'a');
// => false
```

**Comment by joshghent** [comment]
Great idea @asiyani!

We should probably have an option to add libraries which will open a modal dialogue. We can then have the user put in a link to the JS file they want. In addition to this we can have some preset ones like Lodash etc.

Checkout [codepen.io/pen](http://codepen.io/pen) and click on settings > javascript to see what I have in mind.

**Comment by asiyani** [comment]
yes, but problem with adding own library in like in codepen is you need to write some boilerplate code before you can actually do what you wanna do. 
Atleast in most used library user should be able to just select library and start writing actual code. 
e.g. -> user will select lodash -> then just write console.log( _.now() )  this should work. 
So we will have to do all background work like requiring lodash and assigning it to _ var.  [runkit Link](https://runkit.com/588fbb63bd7a7e0015e6cc38/589059be22b7750014103c2e/branches/master)

**Comment by joshghent** [comment]
@asiyani Yeah that sounds a good idea. Yeah I think we can stick with the UI we have but skirt over the boilerplate that codepen requires.

**Comment by velascoDev** [comment]
@joshghent I think we should use jQuery to handle this. This method is perfect for it: http://api.jquery.com/jQuery.getScript/

I can go ahead and implement it, if you want.

**Comment by joshghent** [comment]
Hmm, I'm not sure about including the entire jquery library for one method.
Is there anyway we can require a single method of jquery like with lodash?
I'd ideally like to make sure the site is as light weight as possible.

How would you go about loading the library in? Perhaps we can checkout
using the cdnjs API to get a CDN link to all the libraries we will support
(lodash, underscore etc.)

What are your thoughts?

-- 
Josh Ghent

**Comment by velascoDev** [comment]
I was thinking of doing something like this: http://codepen.io/velascoDev/pen/wgbZQL?editors=1111
but I'm not sure if it would work with the babel compiler. 
Idk about just one method, but using this approach: http://developer.telerik.com/featured/jquery-using-only-what-you-need/
we can require only the jQuery AJAX module, which is 13K when compressed.

**Comment by velascoDev** [comment]
As for using the cdnjs API, I'm not sure about how to execute the response file properly. How would you go about that?

**Comment by joshghent** [comment]
@velascoDev Sorry for not getting back to you. I would run a query for the library that the user requested and then get the URL of that library and load it in as a script element. 

I'm not 100% sure however as in the case of some libraries there are multiple prerequisites. For example to load bootstrap.js you first need jquery.

I'll have a think about how best to go about this. It could be that we have a table of libraries and a link to their CDN file or something like that? Have you had any more thoughts.

Yeah we could require just that module. I'd prefer if we could do this all in JS but if it significantly helps then that would be the route to go (importing just the methods we need)

**Comment by asiyani** [comment]
found this [blog](https://www.nczonline.net/blog/2009/07/28/the-best-way-to-load-external-javascript/) it addes script tag to head and calls callback function
Implemented same using cdnjs Not sure how to load specific version for the best way we can implement that....[code pen](url)
I think if we do this way we might have to remove script tag from head once fiddle is done or new fiddle is loaded.

**Comment by joshghent** [comment]
@asiyani Yeah I'm happy with this approach. Is that something you or @velascoDev would be up for doing?

**Comment by isaeef** [comment]
@joshghent  is it still open? I am up for it.

**Comment by joshghent** [comment]
@isaeef Yes this is still open, we would really appreciate you're help on this one! Let us know how you get on 👍

**Comment by phsantiago** [comment]
We can get a js file by xmlhttprequest and eval it, or create a dynamic script tag like @asiyani said

**Comment by joshghent** [comment]
@phsantiago I think a dynamic script tag would work best and be most safe. `eval` scares me.

**Comment by jigar1101** [comment]
@joshghent Can you please check #174 
Based on the discussion you and @asiyani had, I have added this which can be improved based on your inputs.

**Comment by joshghent** [comment]
@jigar1101 @asiyani Updated the PR with some comments. Looks like it will need catching up with the latest version of the `develop` branch where I have fixed babel but looks great! 💯 Thank you so much for this work! 🎉

**Comment by jigar1101** [comment]
Great 👍
