### ISSUE TITLE
Cache images folder

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#48]
Using some kind of express caching middleware (it doesn't matter what, I saw express-cache-control but there are others), make the /images/ directory cache for a month.

This will improve load times for users as images are probably the largest asset on the page.

**Comment by ironprice91** [comment]
@joshghent I'd like to work on this

**Comment by joshghent** [comment]
@ironprice91 Of course! All yours! We look forward to your PR 👍

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/51
Thanks @ironprice91 🎉
