### ISSUE TITLE
Dynamically show the Login and Logout buttons

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#49]
We have now implemented github login on the develop branch.

We have three buttons on the main index.html page (the code page) - Login, Logout and View Profile.

If a user is logged in we should show the Logout and View Profile button.

If they are not logged in then show the Login button.

Speak to @asiyani about how to detect if the user is logged in on the front-end.

**Comment by anish-shekhawat** [comment]
Hey @joshghent, I would like to work on this!

**Comment by joshghent** [comment]
@anish-shekhawat All your amigo!

**Comment by asiyani** [comment]
@anish-shekhawat how it's going? Do you need any help?

**Comment by anish-shekhawat** [comment]
Hey @asiyani, couldn't work on it last week due to a class project. I am working on it now. Thanks for the help! I will let you know if I get stuck!

**Comment by anish-shekhawat** [comment]
Hey @asiyani can you help me out with the login part?

**Comment by asiyani** [comment]
ya sure, if you are using template on server side you can use `req.isAuthenticated()` which will return true for logged in user.
OR we can create API to find out if user is logged in or not from Client side.

**Comment by joshghent** [comment]
I'd like to do templating as it might be useful in the future but I believe an API to check whether the user is authenticated could be useful.

Ideally go with templating as it will mean greater security. It's a bigger job but would be very useful.

**Comment by anish-shekhawat** [comment]
Thanks! @joshghent and @asiyani. I will go with templating then.
