### ISSUE TITLE
Output browser errors to the console on the page

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#5]
If you write some code in ESfiddle that has a JS error in it, the error will not be printed to the on screen console. This is functionality we definitely want to have.

Ideally this should also have tests against it but these can be added later.

Check this case here https://esfiddle.net/ixwfnfo5/

**Comment by dr4ke90** [comment]
Hi :-)

First timer here. Is there an official process on how to request a bug? Would like to try my hand at this one.

**Comment by joshghent** [comment]
@OmisNomis Hi there! Great to have you here.

If you want to report a bug then [create a new issue.](https://github.com/esfiddle/esfiddle/issues/new)

If you want to fix a bug and help out with the project, then fork the project, make your changes then submit a pull request for the project. Let me know if you need any more help with this 😁 [Here is a pretty good guide](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/)

**Comment by OmisNomis** [comment]
Thanks @joshghent - it was the latter; I'm hoping to try my hand at helping. 

I'll take a look and hopefully submit a pull request soon. Thanks again!

**Comment by joshghent** [comment]
@OmisNomis Brilliant, I look forward to it! 
Thanks for your help!

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/26
