### ISSUE TITLE
Design documentation

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#53]
Originally the site was one single page, as we are growing the number of pages we need to have a consistent look and feel to each of them.
This is a reasonably big task but do not be put off as it can be done by many different people. **If you have an eye for design this is for you!**

What we require is documentation on how we can make the pages look consistent (for new contributors if they are creating new pages). This documentation may require writing some new css or improving our old stuff to make sure that it's easy to use the various classes throughout the site.

How specific we are with this documentation is another question. Initially it does not really matter, as long as it's there and useful. We can also drill down into the nitty gritty such as exact letter spacing and stuff later.

For now all we really need is, here is how an average page should look (perhaps with a screenshot). here's how it should be structured code wise and then some css classes to use to add that styling.

**Comment by SaraVieira** [comment]
I will start this tomorrow and this will be done as a part of the creation of the new theme for ESFiddle, if anyone wants to join they are more than welcome to

**Comment by csdeshpande19** [comment]
I would like to help. Its my first PR so can you please guide me through. @SaraVieira @joshghent

**Comment by SaraVieira** [comment]
Hello @csdeshpande19 ,

This one is a big one and there is still some designing to do so I would start by adding some examples to get started into the open source world 😄 

Thank you again man

**Comment by csdeshpande19** [comment]
Yea no problem :)
