### ISSUE TITLE
Move from Stylus to SASS

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#54]
When I inherited the project the styles were written in Stylus. I never knew stylus so I just wrote css in the stylus files basically. I think a lot more people are familiar with SASS (myself included!) and so can take full advantage of the features that SASS offers.

A PR for this issue would include moving all our .stylus files over to sass files and configuring that in the build process (including the watch task).

**Comment by babzcraig** [comment]
Hello @joshghent. I'd like to take up this issue. Also, do you need any help with the front end design? I can help with general layout, spacing etc. Let me know

**Comment by joshghent** [comment]
@babzcraig Hi there, thanks for your interest. This issue is already being handled here https://github.com/esfiddle/esfiddle/pull/58

We do definitely need help with the front end however. We do not have designs set in stone so you are free to design yourself! The entire login area for users needs redesigning. Perhaps talk with @SaraVieira as she seems to be heading up the redesign. :+1:

**Comment by joshghent** [comment]
We ended up porting to LESS. Thanks to @SaraVieira for doing that. 
Fixed in https://github.com/esfiddle/esfiddle/pull/58
