### ISSUE TITLE
Rename and sort folder structure

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#55]
I've noticed that the whole folder structure we have for the project might be a bit confusing. Some people initially think that we should change things in static/ (which was true for a while). Nonetheless, I think this could be done to be much less confusing.

I was thinking of doing the following changes
- Rename static to 'dest' or 'dist'
- Create a folder inside 'src' for 'js' and 'views'
- Move api.js to a 'server' folder
- Move all docs (apart from README) into a docs folder.

This might be quite a big job as all the file paths will need renaming. Please make sure you test throughly before submitting a PR! 💃

**Comment by amandaporto** [comment]
I'd like to take a shot at this in the next few days :)

**Comment by joshghent** [comment]
@amandaporto Brilliant, look forward to your PR 👍  Let me know if you need any help.

**Comment by SaraVieira** [comment]
@amandaporto Are you still working on this ?

**Comment by amandaporto** [comment]
Yes @SaraVieira! This past weekend was a bit busy. Will try to get it done asap.

**Comment by SaraVieira** [comment]
Awesome 🎉 

And don't worry, you have time 😄

**Comment by vcapretz** [comment]
@amandaporto hey Amanda, how are you? 

just reminding you that if you need any help just let us know! thanks for working on that

**Comment by amandaporto** [comment]
Should I keep the LICENSE file in the root with the README, or do you also want it inside the docs folder?

**Comment by vcapretz** [comment]
@amandaporto I think you could keep the LICENSE file under the root :smiley: 

in the `src` folder there's also a `examples` folder containing some JS files, those ones and the authenticated.js should be inside the `src/js` folder! 

thanks for helping!

**Comment by amandaporto** [comment]
You still want to keep the `example` folder, but just under `src/js`, correct? And just to double check, authenticated.js goes in that folder, but not index.js. 

I should be mostly done after this. PR should be coming soon.

**Comment by vcapretz** [comment]
@amandaporto yeah! that's right.

why not index.js? I think it would make sense to put it under the `src/js` folder

**Comment by amandaporto** [comment]
No particular reason, it was just how I understood what you said :) PR #92
