### ISSUE TITLE
Improve score on the Google mobile friendly test

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#56]
https://search.google.com/search-console/mobile-friendly?id=EqQWeljAIXs06Nr6Luca4A

All the issues are there really, they need addressing.

A good change would be for mobile devices to default to the horizontal view if it's between a certain width. On tablets (in landscape) you can probably use it in the vertical view but with thinner screens it would look cramped by default and not user friendly.

You have free reign on how to fix these issues as long as they look nice 👍

**Comment by SaraVieira** [comment]
I can work on this it sounds pretty fun.  
But I would like to know if I structure the CSS first? 
That file is in big file man :p

You also have a issue to move from stylus to SASS,  can I move it to less instead?  Pretty please?  :p

**Comment by joshghent** [comment]
@SaraVieira Yeah we need to restructure the CSS for sure. More modular I think definitely. 
Hmm im not sure, why do you say Less over SASS? I really only went with SASS due to its high usage and familiar syntax for me.

**Comment by SaraVieira** [comment]
That was my ideia with the CSS, separate that.

I have been using less for years, I guess it's just a matter of preference and proficiency, I would be faster using less than SASS but I can use SASS 👍

**Comment by SaraVieira** [comment]
![screen shot 2017-02-22 at 11 51 51](https://cloud.githubusercontent.com/assets/1051509/23210409/582117ac-f8f5-11e6-994b-a9bba9049961.png)


Is something like this something you would like ?

**Comment by joshghent** [comment]
@SaraVieira Yeah I don't mind LESS if you are familiar with it. The important thing is too moderlize so it's easier to maintain in the future. And also rename classes and IDs so they are easier actually see what they are doing. 

Yeah that looks good. Needs tweaking but on the whole that's pretty much it. Not much of our traffic is on mobile so we do not need to worry too much.

**Comment by SaraVieira** [comment]
Okay , I'm going to divide this in to three pull requests, one for the LESS & lessLint, then the mobile one that will look something like this on phone but with a few tweaks on the head.

Later when did this approved I can try to work on the design documentation to make the site more consistent, does that sound okay to you ? 🎉 

@joshghent

**Comment by joshghent** [comment]
Sounds great. Best to do it in small steps! Thanks @SaraVieira :+1:

**Comment by SaraVieira** [comment]
Pull request for LESS created :)

**Comment by SaraVieira** [comment]
I'll start doing little steps of redesign and mobile design and post pictures here so people can give their input, is that okay?

I'm really liking working on this project 🎉 
this will also affect issue #53

**Comment by joshghent** [comment]
@SaraVieira Yeah that would be great. I prefer seeing the visualize so that would be great. Design docs would be fantastic too, let me know if you have any questions about all this.

Glad to hear it! We're liking you work on the project too! 💯  Let me know if there is anything else we can help with 👍
