### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#59]
As we are getting more contributors we need a code of conduct to ensure we have a welcoming environment for the community. ESFiddle should be accessible to anyone regardless of background, race, gender or, when the aliens come, what planet they are from.

We need to add a new CODE_OF_CONDUCT.md file with the contents from [here](http://contributor-covenant.org/version/1/4/code_of_conduct.md)

**Comment by tarang9211** [comment]
I got this

**Comment by tarang9211** [comment]
Wait I thought I was picking this up josh?

**Comment by joshghent** [comment]
@tarang9211 Apologies I didn't realise the time difference between us! I wanted to get these changes out the door and thought you may have just got busy. My mistake. Sorry about that! 😨
