### ISSUE TITLE
Add browser-sync + watch task for grunt

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#6]
When developing ESFiddle we want to be able to change one of the files that gets compiled (like the stylus styles and JS) and see that immediately. 
Let's add some browser-sync magic and have it watch the CSS and JS files and automatically rebuild them if they change.

**Comment by tarang9211** [comment]
@joshghent Maybe this is better to tackle now rather than later. What should I be looking up to get started?

**Comment by joshghent** [comment]
@tarang9211 Basically we need browser sync configuring so it will check the JS and stylus files for changes and rebuild the new css and compiled js. It then needs to reload the browser of the client connected to it (you might have to do this with the "proxy" option but have a play around)

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/41
