### ISSUE TITLE
Update travis node versions

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#61]
In travis.yml we need to set the versions of node that travisCI will run our test suite against.

We want to support all the node versions that are still actively maintained by the node community as well as the latest current version.

Check out[ this repo](https://github.com/nodejs/LTS) for a list of node versions that are still active. 

Using the list there, please update the travis.yml with these node versions.

**Comment by musicionary** [comment]
@joshghent I'd love to help on this.  I've looked at the repo you linked, and the travisCI docs.  Just to clarify, are you looking for the file to be update only with major release versions, or minor release versions as well?

**Comment by joshghent** [comment]
@musicionary Just major versions please. Thanks a lot. Look forward to your PR 👍

**Comment by musicionary** [comment]
@joshghent I submitted a PR and the Travis build didn't pass with all versions in the update travis.yml (only current, v7, and v6).  I'm adding '.x' in the file to see if that makes the builds pass, but the logs in the Travis builds report errors from a missing npm module or some unexpected token.  Looking into those before I submit another PR

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/67
Thanks to @musicionary for his work 🎉 
Look forward to your future contributions! Let us know if you need any help! 👍

**Comment by musicionary** [comment]
Thanks @joshghent for letting me help!

**Comment by joshghent** [comment]
@musicionary Pleasure is mine! We'd be very happy to have you work with us again! 👍
