### ISSUE TITLE
Add trevor to dev dependencies 

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#62]
Super simple one here, add [trevor](https://github.com/vadimdemedes/trevor) to the dev dependencies and make sure the travisCI suite runs.

**Comment by SaraVieira** [comment]
on it 👍

**Comment by SaraVieira** [comment]
@joshghent Are the node tests passing on your machine ?

**Comment by joshghent** [comment]
@SaraVieira Yeah they are pretty much all passing apart from a few that are pending. They passed on travis when they were run last time so they _should_ be working 😁

**Comment by SaraVieira** [comment]
closed by #65
