### ISSUE TITLE
Add pre-push to run travis test suite

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#63]
In connection with #62 we want to add a pre-push script to run the test suite on all the node versions we support.

#62 will have added trevor which allows for running travis locally in essence. Before a project contributor pushes to their remote branch we want to make sure the test suite passes. Add [this](https://github.com/clearhead/pre-push) to the dev dependencies and configure it to run trevor.

**Comment by SaraVieira** [comment]
As discussed previously I created a pre-push with grunt test, when we add more tests we just need to add them to that task
https://github.com/esfiddle/esfiddle/pull/79
