### ISSUE TITLE
ES6 Rewrite

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#64]
Big one here!
This is a two step process.

1. Rewrite /src/es6-fiddle.js to be in ES2015+
2. Add a babel task to compile this js to ES5 code and add it to the watch task so that we can make changes and not have to restart the server.

Big one here but good fun. Make sure to test throughly!

**Comment by siddharthkp** [comment]
I'm up for it, if it's cool with you

**Comment by joshghent** [comment]
@siddharthkp Of course, we'd be happy to have PR's on this issue! 🎉 
Let me know how you get along 👍 Here is our [Gitter](https://gitter.im/esfiddle/Lobby?) if you have any questions

**Comment by vcapretz** [comment]
hey @siddharthkp let me know if you need help, would like to work on this one as well

**Comment by siddharthkp** [comment]
@vcapretz would you like to code review?

Will complete this tomorrow.

**Comment by joshghent** [comment]
@siddharthkp @vcapretz Sounds great guys, when you submit the PR we can both take a look down and review it. I think we should also be testing locally throughly to make sure everything is still operational (especially cross browser). 
Thanks for your work 👍

**Comment by joshghent** [comment]
@siddharthkp Have you had chance to look at this at all?

**Comment by siddharthkp** [comment]
Yes! I have it all set up, and have made some progress as well

**Comment by SaraVieira** [comment]
@siddharthkp Any help you need just let us know

**Comment by siddharthkp** [comment]
Opened a related issue: https://github.com/esfiddle/esfiddle/issues/85
