### ISSUE TITLE
Automatically redirect http traffic to https

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#7]
For some reason the cloudflare setting for this does work so the solution is to have some JS that checks if we are on http and if so redirect to https. 

If anyone has any other solutions then feel free to do it that way.

PR's welcome!

**Comment by mercyg** [comment]
Hi, I would like to work on this issue is there any guideline for this issue?

**Comment by joshghent** [comment]
@mercyg Hi there, apologies this issue has already been done in another PR. I forgot to close it out. There are plenty of other issues that are free which we would welcome PR's on.

**Comment by joshghent** [comment]
Fixed in https://github.com/esfiddle/esfiddle/pull/9
