### ISSUE TITLE
Eslint giving syntax error for ES6 syntax

### ISSUE THREAD

**Issue by asiyani** [esfiddle/esfiddle#70]
#### Need to configure ESlint to support ES6.

Some of the code on server side is written in es6 syntax,  also we are planning to move front end code to ES6 as well. we need to configure eslint for this.

Also it would be great if we have some sort of provision for future ES versions.

**Comment by vcapretz** [comment]
Working on that!

**Comment by vcapretz** [comment]
@asiyani pull request here: https://github.com/esfiddle/esfiddle/pull/72

**Comment by joshghent** [comment]
Thanks to @vcapretz for his great work! 🎉 
Completed in #72 
Look forward to seeing you soon 👍
