### ISSUE TITLE
Split app.js route down

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#73]
The main app.js file has become a little unwieldy and needs breaking down.

I'd suggest breaking it down into the following inside of a 'routes' folder.
* Main page route (embeded and regular)
* Authorised routes (github login etc)
* Other pages like the blog and about

Make sure that all the api tests work after you do this!

**Comment by Kashyap12** [comment]
hi @joshghent , can i take this up?

**Comment by joshghent** [comment]
@Kashyap12 Of course! All yours! Let me or anyone else know if you have any questions 👍 
Look forward to your PR 🎉

**Comment by SaraVieira** [comment]
Hello @Kashyap12 ,

Are you still working on this ? 😄

**Comment by Kashyap12** [comment]
@SaraVieira yes

**Comment by Kashyap12** [comment]
@joshghent Hi Josh, I ve started working on this issue, but need help as I am a bit new to OSS ans JS, please let me know if we can have a chat.

**Comment by vcapretz** [comment]
@Kashyap12 what's your doubt? try to explain here and I'll try to help you

**Comment by Kashyap12** [comment]
@vcapretz so I hv one doubt ,in the break up of the app.js script,the 1st point is ,Main page route  (embeded and regular),I am nt sure what is embeded and regular.

**Comment by vcapretz** [comment]
@Kashyap12 I think it makes sense to put the "embed" routes (they are using Regular Expressions), the authenticated/ route and the ones that have comments starting with "// This one is matching ...".

Not every page will need to have all of that imports, probably just the main page route! 

(if you need an example, that a look here: https://github.com/vcapretz/task-manager/tree/master/routes, it was a project that I made to practice Node!)

**Comment by joshghent** [comment]
@Kashyap12 @vcapretz Yeah I would split the routes down like that. 

* Authenticated routes
* Login routes (we will be adding more ways to login so will need different end points soon)
* Static pages (blog and about) 
* Code pages (embedded and homepage).

**Comment by vcapretz** [comment]
I'm doing this one! will send the PR soon
