### ISSUE TITLE
Add new example code

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#74]
One of the main focuses of ESFiddle is to have a rich library of example code for ES2015+.
It would be great to expand this collection of code even further and improve the current code we have.

If you can think of a code example to demonstrate a new ES2015 or ES2016 feature then write it in the 'src/examples' folder and then submit a new PR! 🎉 

**We will be accepting multiple PR's for this so anyone can get going!**

**Comment by csdeshpande19** [comment]
Hi. I'm a newbie. Can you help me. I would like to contribute.

**Comment by SaraVieira** [comment]
Hello @csdeshpande19 ,

It's awesome you want to help 🎉 

If you want to add more examples just head over to websites like:
[https://github.com/vasanthk/es6-examples](https://github.com/vasanthk/es6-examples) and get some exmaples there.

To add it to the site you can clone the repo and then in the src/examples folder there is a ton of examples you can see. Simply add new ones with that structure .

Any questions ask 👍

**Comment by csdeshpande19** [comment]
OK Ill start working on this today. Ill make a PR then !

**Comment by djw11192** [comment]
Hello @joshghent.  I am looking to make my first contribution to open source.  Can I also work on adding some examples?

**Comment by vcapretz** [comment]
Hi @djw11192 how are you? Sure you can add more examples! We are very excited to receive your PR! 

Thank you for your support! 🎉

**Comment by joshghent** [comment]
@djw11192 as @vcapretz we are still happy to accept PR's on this issue!

This is an ongoing project to provide the best example ES6 and ES7 code on the web.

We look forward to your PR 👍

**Comment by HussainAliAkbar** [comment]
Hello! hope you guys are doing good. 
hoping to submit a PR for this issue soon.

**Comment by joshghent** [comment]
@HussainAliAkbar Brilliant! Sounds great! Look forward to it 👍

**Comment by sanggonlee** [comment]
Hi,
I created a PR for updating the example code for promises. Let me know if this can be further improved or any feedback. (Also this is my first contribution to an open source project ever so please let me know if I've done something weird)

**Comment by joshghent** [comment]
@sanggonlee It looks great! Thank you very much for your submission. I'll review this code tomorrow and test it locally. Looks good though!

Take a look at our other issues in the mean time and grab anything you like!

**Comment by Dianna** [comment]
@joshghent would you still like more examples?

**Comment by joshghent** [comment]
@Dianna Yes that would be fantastic! We also have other issues to work on if you'd like to have a crack at those 👍

**Comment by Dianna** [comment]
Great! I've made PR. It looks like people are already tackling the issues I've checked out. Want to link me to an issue that's taking longer than you expected? 😉
