### ISSUE TITLE
Create CSS Regression tests

### ISSUE THREAD

**Issue by SaraVieira** [esfiddle/esfiddle#78]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description

Create regression tests to test when someone makes any changes it does not break the layout

Also add this to Travis and pre push hooks alongside with lint

**Comment by eugenefedoto** [comment]
@SaraVieira are you working on this?

**Comment by eugenefedoto** [comment]
@joshghent any idea if I can try this? Not sure if @SaraVieira is still working on it.

**Comment by joshghent** [comment]
@eugenefedoto Apologies for not getting back to you!

Yeah go for it, @SaraVieira is very busy. I've just removed her as being assigned. We'd love to have you on board helping us! We really appreciate all the help we get! 👍

**Comment by eugenefedoto** [comment]
I'll look into it.

**Comment by joshghent** [comment]
@eugenefedoto Brilliant, thank you very much for looking into this 👍
