### ISSUE TITLE
Use template literals for cleaner examples code

### ISSUE THREAD

**Issue by siddharthkp** [esfiddle/esfiddle#85]
#### Type of issue
- Bug
- [x] Idea/Suggestion
- Question

#### Description (include any screenshots or debugging information if applicable)

For examples, there are code samples that are copied. The code for copying these look something like this:

```js
// src/examples/arrow-example.js

window.es6Example.arrow = {};

window.es6Example.arrow.code = [
    'let square = x => x * x;',
    'let add = (a, b) => a + b;',
    'let pi = () => 3.1415;',
    '',
    'console.log(square(5));',
    'console.log(add(3, 4));',
    'console.log(pi());',
    ''
].join('\n');

window.es6Example.arrow.display = 'Arrow Functions';
```

As you can see there are commands that are joined into a string and returned. The readability of this can be enhanced by using template literals ``

```js
// src/examples/arrow-example.js

window.es6Example.arrow = {};

window.es6Example.arrow.code = `
      let square = x => x * x;
      let add = (a, b) => a + b;
      let pi = () => 3.1415;

      console.log(square(5));
      console.log(add(3, 4));
      console.log(pi());

`;

window.es6Example.arrow.display = 'Arrow Functions';
```

https://github.com/esfiddle/esfiddle/pull/81 does some of the ground work for using them.

**Comment by joshghent** [comment]
@siddharthkp Great idea! Thanks a lot!

We will be accepting PR's on this from anyone! Let me know if you need any help.

**Comment by shaktisri** [comment]
Hi,
 I would like to work on this. Can I give it a go?

**Comment by shaktilucifer** [comment]
Hi,
I would like to work on this. Can I give it a go?

**Comment by joshghent** [comment]
@shaktilucifer Absolutely! All yours friend! We'd be happy to welcome your PR 👍
Please keep us up to date and let us know if you need any help 😀

**Comment by shaktilucifer** [comment]
@joshghent  I did a pull with the recent changes to test the examples. The examples drop down does not seem to populate with values now. Is this a bug ?

**Comment by joshghent** [comment]
@shaktilucifer Try and pull it down now. It was broken briefly in a pull but it should be fixed now.

**Comment by shaktisri** [comment]
Alright awesome . Thanks. I ll check it out
