### ISSUE TITLE
Add line number for corresponding console.log() statement in console section.

### ISSUE THREAD

**Issue by asiyani** [esfiddle/esfiddle#91]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)

Just a thought, I think we should add line numbers for corresponding console.log() statement to console page/section on right. 

At the moment it looks like this....
![screen1](https://cloud.githubusercontent.com/assets/7142320/23525167/6b6e877c-ff85-11e6-9f6b-47070736f5b4.png)

If want to find out which one is true for false, I have to literally count output line  and then console.log statement! 

So what i am suggesting is following.....
![screen2](https://cloud.githubusercontent.com/assets/7142320/23525399/479fba2c-ff86-11e6-85d2-654dc6609060.png)

**Comment by joshghent** [comment]
@asiyani I like the idea but the reachings of this are quite broad and could possibly produce incorrect results. In addition to this I don't think with code mirror we can actually get the line numbers out with the code. I'll have to look into this though.

Great idea! Now just to see if it's possible... at the moment. Nothing is impossible after all 👍

**Comment by asiyani** [comment]
True i have no idea how we can implement this but lets see what we can do...
