### ISSUE TITLE
Add ability to make a fiddle private

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#96]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Add a new icon to the fiddle code window. The icon should be similar to the incognito man, perhaps use this [icon](http://fontawesome.io/icon/user-secret/). This option should only show to signed in users.

Make it so that when the user clicks that button it marks the fiddle as private.

To do this you will need to do the following:
- Add a new DB column to the fiddles table called 'isPrivate' (this should be a boolean)
- Add an api route to make the fiddle ID private
  - In that route, get the fiddle record and make the isPrivate column set to either 1 or 0 (1 = Private, 0 = not private)
- Add logic into the main fiddle route to check if the user that is trying to view the fiddle is the person who created that fiddle. If they are not the user who created it, return an error saying that the fiddle is private.

**Comment by asiyani** [comment]
I will start working on this....

**Comment by Baidaly** [comment]
@asiyani Are you still working on it? If not I could work on this.

**Comment by Baidaly** [comment]
It's been awhile since @asiyani started working on this. Can I have a try to work on this? @joshghent
