### ISSUE TITLE
Export as Gist

### ISSUE THREAD

**Issue by joshghent** [esfiddle/esfiddle#98]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Add a new button in the share menu to export the fiddle to a gist.

The exported gist will include a comment before it that links to the fiddle on esfiddle. 
like this:
```js
/**
   Exported from ESFiddle.net
   Check it out here https://esfiddle.net/abcdefg
**/

function a(){
console.log("hello world")
}
a();
```

This issue will require a new route to handle api requests to share to github gists.

Clicking the button will call the github api and export the fiddle to the users github account. This option will only be displayed for users that are logged in.

**Comment by shaktilucifer** [comment]
@joshghent  Can I take this ?

**Comment by vcapretz** [comment]
Sure @shaktilucifer! Glad to know that you are interested in helping! If you need any help just let us know!

Looking forward for you PR

**Comment by vcapretz** [comment]
@shaktilucifer how are you? Are you still working on this? If so, let us know if you need any help :smile:

**Comment by shaktilucifer** [comment]
Yup still working on it. Reading through the code to get a sense of how everything works. I ll hit you guys up if I am stuck somewhere. Thanks!

**Comment by shaktilucifer** [comment]
@joshghent I think the  current build seems to have issues with login and the share button seem to be missing . It seemed fine with my older branches.

**Comment by joshghent** [comment]
@shaktilucifer Hmm ok, have you tried pulling down the latest version of the develop branch? Do `git fetch origin` and then merge the develop branch into your local branch.

The share button only appears when you have saved a fiddle. The login button should be there apart from when you are logged in.

Let me know if you still run into issues and I will look into it more indepth.

**Comment by JeffKandel** [comment]
@joshghent I am going to work on this issue.  I see there was some previous work on it, so if anyone would like to check in with me, I'm available on gitter!

**Comment by JeffKandel** [comment]
Trying to think through how to authenticate as a user from our server. Will post in gitter if I remain stuck.

**Comment by JeffKandel** [comment]
Solved the issues I was facing!
